//! Constant-array promotion: fully-constant local arrays → `.rodata` globals.
//!
//! A local array initialized entirely by constants and only ever READ is a
//! C-level constant, but the pipeline still materializes it as an alloca
//! plus one store per element — 48 scalar `movb`s for vecreg_new_ops'
//! three 16-byte arrays, ~100 stores for a dispatch table — where GCC and
//! Clang emit the bytes once in `.rodata` and reference them
//! rip-relatively. The stores survive every pass because each is a
//! legitimate store to a legitimate alloca; nothing before codegen ever
//! asks "is this whole object a constant?".
//!
//! After full unrolling + SCCP + copy propagation, the surviving shape of
//! such an array is exactly:
//!
//! - one `Alloca` of `size` bytes;
//! - stores whose pointers are the alloca itself or a constant-offset GEP
//!   of it, and whose values are all `Const` — with the stored byte ranges
//!   tiling `[0, size)` completely and without overlap;
//! - every other use of the array's ADDRESS either loads from it or passes
//!   it to a direct callee that provably never writes through that
//!   parameter.
//!
//! The transform replaces the alloca with a fresh `is_const` global
//! (`.LCA_n`, following the `.LCVEC` naming convention, generated by
//! probing the set of occupied names so sparse pre-existing labels cannot
//! collide) carrying the bytes as a `GlobalInit::Array` of `I8`,
//! substitutes a `GlobalAddr` for every address use, and deletes the
//! initialization. The backend's existing global + GEP folding then emits
//! `tbl+N(%rip)` operands.
//!
//! Soundness contract (fail-closed; a candidate failing any check keeps
//! its alloca):
//!
//! 1. **Exact tiling.** The stores' `[offset, offset+width)` ranges must
//!    cover every byte of the object with no gaps (uninitialized bytes
//!    would change semantics) and no overlap (two stores to one byte means
//!    the later value wins — orderable in principle, but the folded single
//!    value would have to be proven; reject instead).
//! 2. **Dominance.** All initialization stores must live in one block that
//!    dominates every block containing an address use — a conditionally
//!    initialized array is not a constant. (A store whose value is only
//!    conditionally *computed* is fine: SCCP has already folded it, or the
//!    value is not a `Const` and the candidate dies on that store.)
//! 3. **Read-only address discipline, by provenance.** The address may
//!    reach a `Load` pointer or a direct-call argument through ANY chain
//!    of address dataflow — constant- or variable-offset GEPs, pointer
//!    casts, copies, phis, selects — and every such mention is resolved
//!    through `pointer_touches`; the rewrite substitutes the `GlobalAddr`
//!    through the same chains (the IR's pointers are untyped
//!    `IrType::Ptr`, so the substitution is type-exact at every hop). A
//!    `Store` through any pointer that may touch the object with a
//!    non-`Const` value (or at an unresolvable offset) rejects it:
//!    `a[k & 3] = v` is a runtime write and the object is not a constant.
//!    Any mention in a non-whitelisted position — stored to memory,
//!    returned (terminators are audited: `return a;` once left a dangling
//!    reference to the deleted alloca and ICE'd the backend), passed to an
//!    indirect call or an extern, used in arithmetic, fed to a `Memcpy`,
//!    an atomic, or inline asm — rejects the candidate.
//! 4. **Callee write-through proof.** For a direct-callee argument, the
//!    callee must be a non-weak definition in this module (a weak symbol's
//!    linked body may be a strong override that writes — the same rule the
//!    inliner and `ip_purity` apply, with the kernel vmemmap_set_pmd
//!    failure documented there), and its parameter (the unique `ParamRef`
//!    at that index) may only flow into `Load` pointers, through
//!    pointer-preserving address dataflow (pointer-to-pointer `Cast`s,
//!    `GEP`s of ANY offset, `Phi`s/`Select`s/`Copy`s of derived pointers —
//!    a loop strength-reduced to pointer induction merges the preheader
//!    pointer with the backedge GEP; the phi *may* carry our object on
//!    some path, so writes through it still reject), and into `args`
//!    positions of intrinsics classified as read-only memory pointers
//!    (`IntrinsicOp::reads_pointer_arg` — the load families and the
//!    memory-foldable vector families; everything else, including the
//!    `BuiltinSetjmp` jump-buffer class and scalar pure ops like `Crc32`,
//!    rejects). The moment the address crosses into a non-pointer domain
//!    (a pointer-to-integer cast), the value becomes OBSERVABLE: any use
//!    of that integer other than casting back to a pointer rejects the
//!    proof — promotion must not change what the program can observe about
//!    the address. A store through any derived pointer, a pass-on to
//!    another call, or any other consumption rejects the candidate at the
//!    call site. The check is deliberately non-transitive: a param
//!    forwarded to another function's param is rejected rather than
//!    transitively proven.
//! 5. **Volatile stores never participate** (a volatile store is
//!    observable); atomic accesses reject the candidate outright.
//! 6. **Alignment is preserved.** The promoted global keeps the alloca's
//!    alignment (`int[2]` stays 4-byte aligned; `_Alignas` is honored):
//!    `.rodata` placement at align 1 would silently turn every aligned
//!    access unaligned. The backend's `effective_align` still applies the
//!    size ≥ 16 → 16 promotion, matching GCC/Clang.
//! 7. **A read is required.** A write-only object whose stores tile it but
//!    which no load or read-only call ever touches is dead weight, not a
//!    constant: promoting it would materialize a permanent `is_used`
//!    `.rodata` global nothing references (initialization GEPs alone do
//!    not count as reads).
//!
//! Pass name for `CCC_DISABLE_PASSES`: "constarr".

use crate::common::fx_hash::{FxHashMap, FxHashSet};
use crate::common::types::IrType;
use crate::ir::intrinsics::IntrinsicOp;
use crate::ir::module::{GlobalInit, IrGlobal, IrModule};
use crate::ir::reexports::{Instruction, IrConst, IrFunction, Operand, Terminator, Value};

/// A store into a candidate array: `(byte_offset, width, constant)`.
struct ByteStore {
    offset: i64,
    width: u32,
    value: IrConst,
}

/// The load/store width in bytes of an IR integer type (the only store
/// types this pass consumes).
fn int_width(ty: IrType) -> Option<u32> {
    Some(match ty {
        IrType::I8 | IrType::U8 => 1,
        IrType::I16 | IrType::U16 => 2,
        IrType::I32 | IrType::U32 => 4,
        IrType::I64 | IrType::U64 => 8,
        _ => return None,
    })
}

/// Render a stored constant as `width` little-endian bytes.
fn const_bytes(c: &IrConst, width: u32) -> Option<Vec<u8>> {
    let v: u128 = match c {
        IrConst::I8(x) => *x as u128,
        IrConst::I16(x) => *x as u128,
        IrConst::I32(x) => *x as u128,
        IrConst::I64(x) => *x as u128,
        IrConst::I128(x) => (*x as u128) & (u128::MAX >> (128 - width * 8).min(127)),
        _ => return None,
    };
    let mut out = Vec::with_capacity(width as usize);
    for i in 0..width {
        out.push(((v >> (i * 8)) & 0xff) as u8);
    }
    Some(out)
}

/// Constant-offset GEP view: dest -> (root base, total offset). Chains
/// collapse iteratively.
fn gep_roots(func: &IrFunction) -> FxHashMap<u32, (u32, i64)> {
    let mut map: FxHashMap<u32, (u32, i64)> = FxHashMap::default();
    // Iterate to a fixed point: a GEP of a GEP resolves once the inner one
    // is in the map (the scan order is not guaranteed).
    loop {
        let mut grew = false;
        for block in &func.blocks {
            for inst in &block.instructions {
                if let Instruction::GetElementPtr {
                    dest, base, offset, ..
                } = inst
                {
                    if map.contains_key(&dest.0) {
                        continue;
                    }
                    if let Operand::Const(c) = offset {
                        if let Some(off) = c.to_i64() {
                            let root = match map.get(&base.0) {
                                Some(&(b, o)) => (b, o.saturating_add(off)),
                                None => (base.0, off),
                            };
                            map.insert(dest.0, root);
                            grew = true;
                        }
                    }
                }
            }
        }
        if !grew {
            break;
        }
    }
    map
}

/// Resolve a pointer value to `(root alloca, byte offset)` when it is the
/// alloca itself or a constant-offset GEP chain above it.
fn addr_of(v: u32, alloca: u32, geps: &FxHashMap<u32, (u32, i64)>) -> Option<i64> {
    if v == alloca {
        return Some(0);
    }
    match geps.get(&v) {
        Some(&(b, off)) if b == alloca => Some(off),
        _ => None,
    }
}

/// The set of candidate allocas a value may point into, resolved through
/// ANY chain of address dataflow — constant- **or variable-offset** GEPs,
/// pointer casts, copies, and phis/selects merging derived pointers (a
/// merge with an unrelated pointer still *may* carry ours on some path,
/// which is exactly the rejection direction needed for stores).
///
/// This is the classification the dereference audit runs on. The original
/// const-offset-only resolution left every variable-offset dereference
/// invisible: `a[k & 3] = v` — a runtime store! — fell through the
/// whitelist's `GEP.base` arm unclassified, so an array whose only other
/// use was a provably read-only callee promoted with the runtime write
/// intact: a store into `.rodata` (SIGSEGV at best, silent corruption in
/// any build that links the section writable). The same invisibility let
/// `Memcopy`/`AtomicStore`/`InlineAsm`-style write positions and
/// `return a;` (a terminator mention) escape the catch-all — the latter
/// left a dangling reference to the deleted alloca and ICE'd the backend.
/// `pointer_touches` closes the whole class: provenance, not spelling.
fn pointer_touches(
    func: &IrFunction,
    allocas: &FxHashMap<u32, (usize, usize)>,
) -> FxHashMap<u32, FxHashSet<u32>> {
    let mut touches: FxHashMap<u32, FxHashSet<u32>> = FxHashMap::default();
    // Seed: each candidate alloca touches itself.
    for &a in allocas.keys() {
        touches.entry(a).or_default().insert(a);
    }
    // Fixed point: sets only grow and are bounded by (values x candidates).
    loop {
        let mut grew = false;
        for block in &func.blocks {
            for inst in &block.instructions {
                let (dest, srcs): (u32, Vec<Operand>) = match inst {
                    Instruction::GetElementPtr { dest, base, .. } => {
                        (dest.0, vec![Operand::Value(*base)])
                    }
                    Instruction::Cast { dest, src, .. } => (dest.0, vec![*src]),
                    Instruction::Copy { dest, src } => (dest.0, vec![*src]),
                    Instruction::Phi { dest, incoming, .. } => {
                        (dest.0, incoming.iter().map(|(op, _)| *op).collect())
                    }
                    Instruction::Select {
                        dest,
                        true_val,
                        false_val,
                        ..
                    } => (dest.0, vec![*true_val, *false_val]),
                    _ => continue,
                };
                let mut union: FxHashSet<u32> = FxHashSet::default();
                for op in srcs {
                    if let Operand::Value(v) = op {
                        if let Some(ts) = touches.get(&v.0) {
                            union.extend(ts.iter().copied());
                        }
                    }
                }
                if !union.is_empty() {
                    let entry = touches.entry(dest).or_default();
                    if union.iter().any(|c| !entry.contains(c)) {
                        entry.extend(union);
                        grew = true;
                    }
                }
            }
        }
        if !grew {
            break;
        }
    }
    touches
}

/// The jump-buffer / apply-area intrinsics that write memory through
/// `args` WITHOUT `dest_ptr` and WITHOUT being listed in
/// `writes_memory_via_args`: exactly the set `Instruction::may_write_memory`
/// adds on top. A callee passing our array to any of these as its buffer
/// writes into the promoted `.rodata`.
fn writes_memory_via_jump_buffer(op: IntrinsicOp) -> bool {
    matches!(
        op,
        IntrinsicOp::BuiltinSetjmp
            | IntrinsicOp::BuiltinLongjmp
            | IntrinsicOp::DoBuiltinApply
            | IntrinsicOp::RestoreApplyResult
    )
}

/// Does `callee` (a function with a visible body in the module) never write
/// through — and never observe the address of — its `arg_idx`-th
/// parameter? Fail-closed: unknown callees, weak definitions, duplicated
/// `ParamRef`s, and any non-load consumption reject.
///
/// Derivations are tracked in two tiers:
///  - **pointer tier**: values that still ARE a pointer derived from the
///    parameter (the param itself, GEPs, pointer-to-pointer casts, copies,
///    phis/selects of pointers). Reads through them are `Load`-classified;
///    they may also feed the read-only memory-pointer `args` positions of
///    `reads_pointer_arg` intrinsics (the folded-load conventions).
///  - **observed tier**: the address crossed into a non-pointer domain
///    (a pointer-to-integer cast). The integer VALUE of the address is now
///    observable — promotion would change what the program computes from
///    it — so any use other than casting back to a pointer rejects.
///    (Re-entry through an int-to-pointer cast returns to the pointer
///    tier, where the ordinary load/store discipline applies.)
fn callee_readonly_through_impl(all: &[IrFunction], callee: &str, arg_idx: usize) -> bool {
    let Some(f) = all.iter().find(|f| f.name == callee && !f.is_declaration) else {
        return false;
    };
    // A weak definition is not necessarily the linked definition: a strong
    // override replaces the symbol at static-link time, so the visible body
    // licenses nothing (inline.rs and ip_purity.rs reject weak bodies for
    // exactly this reason — kernel 6.18's vmemmap_set_pmd page-faulted when
    // a __weak empty body was trusted).
    if f.is_weak {
        return false;
    }
    // NOTE on ELF preemption: a default-visibility non-static body is
    // trusted under lccc's executable-only output model (the executable's
    // own definition wins its internal calls; lccc emits no shared
    // libraries today). If -shared support lands, tighten this gate to
    // non-preemptible definitions (static / hidden / internal / protected).
    //
    // The parameter's SSA value: the ParamRef at this index — exactly ONE.
    // A duplicated ParamRef is a shape this proof does not reason about;
    // fail closed rather than silently auditing the last one.
    let mut root: Option<u32> = None;
    for block in &f.blocks {
        for inst in &block.instructions {
            if let Instruction::ParamRef {
                dest, param_idx, ..
            } = inst
            {
                if *param_idx == arg_idx {
                    if root.is_some() {
                        return false; // duplicate ParamRef — reject
                    }
                    root = Some(dest.0);
                }
            }
        }
    }
    let Some(root) = root else {
        return false;
    };

    let mut ptr_tier: FxHashSet<u32> = FxHashSet::default();
    let mut observed: FxHashSet<u32> = FxHashSet::default();
    ptr_tier.insert(root);
    // Fixed point over the derivation instructions.
    loop {
        let mut grew = false;
        for block in &f.blocks {
            for inst in &block.instructions {
                match inst {
                    Instruction::GetElementPtr { dest, base, .. } => {
                        // Any GEP — constant OR variable offset — is pure
                        // address arithmetic; the write discipline is
                        // enforced at the USES of the derived pointer. (A
                        // constant-offset restriction here rejected the
                        // canonical `for (i=0;i<n;i++) s += p[i];` reader,
                        // starving the whole transform.)
                        if ptr_tier.contains(&base.0) && ptr_tier.insert(dest.0) {
                            grew = true;
                        }
                    }
                    Instruction::Cast {
                        dest, src, to_ty, ..
                    } => {
                        let Operand::Value(sv) = src else { continue };
                        if ptr_tier.contains(&sv.0) {
                            if *to_ty == IrType::Ptr {
                                // pointer -> pointer: still the address.
                                if ptr_tier.insert(dest.0) {
                                    grew = true;
                                }
                            } else {
                                // pointer -> integer: the address VALUE is
                                // now observable.
                                if observed.insert(dest.0) {
                                    grew = true;
                                }
                            }
                        } else if observed.contains(&sv.0) {
                            if *to_ty == IrType::Ptr {
                                // integer -> pointer: re-entry; the ordinary
                                // load/store discipline applies again.
                                if ptr_tier.insert(dest.0) {
                                    grew = true;
                                }
                            } else if observed.insert(dest.0) {
                                grew = true;
                            }
                        }
                    }
                    Instruction::Copy { dest, src } => {
                        let Operand::Value(sv) = src else { continue };
                        if ptr_tier.contains(&sv.0) {
                            if ptr_tier.insert(dest.0) {
                                grew = true;
                            }
                        } else if observed.contains(&sv.0) && observed.insert(dest.0) {
                            grew = true;
                        }
                    }
                    Instruction::Phi { dest, incoming, .. } => {
                        // A phi merging derived pointer(s) with anything else
                        // is a *conditional* derivation: its dest may name
                        // our array on some paths. Keeping it in the pointer
                        // tier preserves the soundness direction (every
                        // write through it rejects) while reads stay allowed.
                        let any_ptr = incoming.iter().any(
                            |(op, _)| matches!(op, Operand::Value(v) if ptr_tier.contains(&v.0)),
                        );
                        let any_obs = incoming.iter().any(
                            |(op, _)| matches!(op, Operand::Value(v) if observed.contains(&v.0)),
                        );
                        if any_ptr {
                            if ptr_tier.insert(dest.0) {
                                grew = true;
                            }
                        } else if any_obs && observed.insert(dest.0) {
                            grew = true;
                        }
                    }
                    Instruction::Select {
                        dest,
                        true_val,
                        false_val,
                        ..
                    } => {
                        // Select's condition never carries a derived
                        // pointer (that would already be an observation);
                        // only the value arms derive.
                        let arms = [*true_val, *false_val];
                        let any_ptr = arms
                            .iter()
                            .any(|op| matches!(op, Operand::Value(v) if ptr_tier.contains(&v.0)));
                        let any_obs = arms
                            .iter()
                            .any(|op| matches!(op, Operand::Value(v) if observed.contains(&v.0)));
                        if any_ptr {
                            if ptr_tier.insert(dest.0) {
                                grew = true;
                            }
                        } else if any_obs && observed.insert(dest.0) {
                            grew = true;
                        }
                    }
                    _ => {}
                }
            }
        }
        if !grew {
            break;
        }
    }

    // Every use must be a memory READ of the pointer tier, and the
    // observed tier must never be consumed at all (except by the
    // int-to-pointer re-entry casts already handled above).
    for block in &f.blocks {
        for inst in &block.instructions {
            match inst {
                Instruction::Load { ptr, .. } => {
                    if ptr_tier.contains(&ptr.0) {
                        continue;
                    }
                    let mut touches = false;
                    inst.for_each_used_value(|id| {
                        if ptr_tier.contains(&id) || observed.contains(&id) {
                            touches = true;
                        }
                    });
                    if touches {
                        return false;
                    }
                }
                // Derivation steps: the GEP's base mention, the Cast's
                // source mention, the Phi's incoming and the Select's arm
                // mentions are how the tiers were built; their DEST is
                // audited wherever it is used.
                Instruction::GetElementPtr { .. }
                | Instruction::Cast { .. }
                | Instruction::Phi { .. }
                | Instruction::Copy { .. } => {}
                Instruction::Select { .. } => {}
                Instruction::Intrinsic {
                    dest_ptr, op, args, ..
                } => {
                    if let Some(dp) = dest_ptr {
                        if ptr_tier.contains(&dp.0) {
                            return false; // writes through our pointer
                        }
                    }
                    let writes_args =
                        op.writes_memory_via_args() || writes_memory_via_jump_buffer(*op);
                    let reads_args = op.reads_pointer_arg();
                    for a in args {
                        let Operand::Value(v) = a else { continue };
                        if observed.contains(&v.0) {
                            // The address crossed into a non-pointer domain
                            // and reached an intrinsic: observable.
                            return false;
                        }
                        if ptr_tier.contains(&v.0) {
                            if writes_args {
                                return false; // args-writing family (incl. setjmp)
                            }
                            if !reads_args {
                                // No classified read-only memory-pointer
                                // position exists on this op; a pointer
                                // argument here is not a memory operand.
                                return false;
                            }
                        }
                    }
                }
                _ => {
                    let mut touches = false;
                    inst.for_each_used_value(|id| {
                        if ptr_tier.contains(&id) || observed.contains(&id) {
                            touches = true;
                        }
                    });
                    if touches {
                        return false;
                    }
                }
            }
        }
    }
    // Terminators cannot legally mention data pointers in this IR, but be
    // fail-closed anyway (either tier).
    for block in &f.blocks {
        let mut touches = false;
        block.terminator.for_each_used_value(|id| {
            if ptr_tier.contains(&id) || observed.contains(&id) {
                touches = true;
            }
        });
        if touches {
            return false;
        }
    }
    true
}

/// Cached wrapper: the proof is a pure function of (callee, arg_idx) within
/// one module snapshot, and a caller with many call sites re-asks per
/// argument — the cache keeps the whole-module audit linear.
fn callee_readonly_through(
    all: &[IrFunction],
    callee: &str,
    arg_idx: usize,
    cache: &mut FxHashMap<(String, usize), bool>,
) -> bool {
    let key = (callee.to_string(), arg_idx);
    if let Some(&v) = cache.get(&key) {
        return v;
    }
    let v = callee_readonly_through_impl(all, callee, arg_idx);
    cache.insert(key, v);
    v
}

/// Audit `func` (read-only, against the whole module for callee proofs) and
/// return every promotable candidate: (alloca id, size, align, byte image).
fn audit_candidates(
    func: &IrFunction,
    all: &[IrFunction],
    proof_cache: &mut FxHashMap<(String, usize), bool>,
) -> Vec<(u32, usize, usize, Vec<u8>)> {
    let mut out: Vec<(u32, usize, usize, Vec<u8>)> = Vec::new();
    // ---- collect candidates ------------------------------------------------
    let mut allocas: FxHashMap<u32, (usize, usize)> = FxHashMap::default();
    for block in &func.blocks {
        for inst in &block.instructions {
            if let Instruction::Alloca {
                dest, size, align, ..
            } = inst
            {
                if *size > 0 && *size <= 4096 {
                    allocas.insert(dest.0, (*size, *align));
                }
            }
        }
    }
    if allocas.is_empty() {
        return out;
    }
    let geps = gep_roots(func);
    let touches = pointer_touches(func, &allocas);

    // ---- per-candidate audit ----------------------------------------------
    let mut stores: FxHashMap<u32, Vec<ByteStore>> = FxHashMap::default();
    let mut store_blocks: FxHashMap<u32, Vec<usize>> = FxHashMap::default();
    let mut use_blocks: FxHashMap<u32, Vec<usize>> = FxHashMap::default();
    // Candidates that survive with at least one real READ (a load, or an
    // argument to a proven read-only callee). Initialization GEPs do NOT
    // count: a write-only object is dead weight, not a constant, and
    // promoting it would materialize an unreferenced is_used .rodata
    // global (no later global-DCE runs).
    let mut read_uses: FxHashSet<u32> = FxHashSet::default();
    let mut bad: FxHashSet<u32> = FxHashSet::default();

    for (bi, block) in func.blocks.iter().enumerate() {
        for inst in &block.instructions {
            // Classification. Every arm FALLS THROUGH to the catch-all
            // below — an early `continue` here is exactly how the escape
            // store (`keep = a`, whose pointer targets a global) skipped
            // its value-side audit once, and a rejected-then-promoted
            // array left an orphaned use that ICE'd the backend.
            //
            // Every arm resolves its pointer through `touches` (provenance
            // through ANY offset/cast/copy/phi/select chain), never through
            // the const-offset-only `geps` view: a runtime store at a
            // variable index must classify as a store, or the object is
            // not a constant.
            match inst {
                Instruction::Store {
                    val,
                    ptr,
                    ty,
                    volatile,
                    ..
                } => {
                    if let Some(ts) = touches.get(&ptr.0) {
                        for &a in ts {
                            if *volatile {
                                bad.insert(a);
                            } else if let Operand::Const(c) = val {
                                if let Some(width) = int_width(*ty) {
                                    match addr_of(ptr.0, a, &geps) {
                                        Some(off) => {
                                            stores.entry(a).or_default().push(ByteStore {
                                                offset: off,
                                                width,
                                                value: c.clone(),
                                            });
                                            store_blocks.entry(a).or_default().push(bi);
                                        }
                                        // A constant value stored through a
                                        // pointer whose offset is not
                                        // resolvable (variable index, or a
                                        // cast/copy/phi-derived base)
                                        // cannot be placed in the image.
                                        None => {
                                            bad.insert(a);
                                        }
                                    }
                                } else {
                                    bad.insert(a);
                                }
                            } else {
                                // A runtime value stored anywhere into the
                                // object: the object is not a constant.
                                // (`a[k & 3] = v` — the variable-offset
                                // GEP is in `touches`, so this now fires.)
                                bad.insert(a);
                            }
                        }
                    }
                }
                Instruction::Load { ptr, volatile, .. } => {
                    if let Some(ts) = touches.get(&ptr.0) {
                        for &a in ts {
                            if *volatile {
                                // A volatile-qualified access keeps the
                                // object in real writable memory; do not
                                // promote what C considers observable.
                                bad.insert(a);
                            } else {
                                use_blocks.entry(a).or_default().push(bi);
                                read_uses.insert(a);
                            }
                        }
                    }
                }
                Instruction::GetElementPtr { base, .. } => {
                    if let Some(ts) = touches.get(&base.0) {
                        for &a in ts {
                            use_blocks.entry(a).or_default().push(bi);
                        }
                    }
                }
                Instruction::Call { func: callee, info } => {
                    for (pos, arg) in info.args.iter().enumerate() {
                        if let Operand::Value(v) = arg {
                            if let Some(ts) = touches.get(&v.0) {
                                for &a in ts {
                                    if !callee_readonly_through(all, callee, pos, proof_cache) {
                                        bad.insert(a);
                                    } else {
                                        use_blocks.entry(a).or_default().push(bi);
                                        read_uses.insert(a);
                                    }
                                }
                            }
                        }
                    }
                }
                _ => {}
            }
            // Catch-all: any mention of a candidate's address value in a
            // position the whitelist above does not cover rejects it. The
            // whitelist positions are: Store.ptr, Load.ptr, GEP.base,
            // direct-Call args (handled above with their own checks), and
            // the ADDRESS-DATAFLOW DERIVATION instructions themselves —
            // Cast/Copy sources and Phi/Select arms — whose results are
            // audited wherever they are used (apply_one substitutes the
            // GlobalAddr through the same chains; the IR's pointers are
            // untyped, so the substitution is exact at every hop).
            let mut ok: FxHashSet<u32> = FxHashSet::default();
            match inst {
                Instruction::Store { ptr, .. } => {
                    ok.insert(ptr.0);
                }
                Instruction::Load { ptr, .. } => {
                    ok.insert(ptr.0);
                }
                Instruction::GetElementPtr { base, .. } => {
                    ok.insert(base.0);
                }
                Instruction::Call { info, .. } => {
                    for arg in &info.args {
                        if let Operand::Value(v) = arg {
                            ok.insert(v.0);
                        }
                    }
                }
                Instruction::Cast { src, .. } => {
                    if let Operand::Value(v) = src {
                        ok.insert(v.0);
                    }
                }
                Instruction::Copy { src, .. } => {
                    if let Operand::Value(v) = src {
                        ok.insert(v.0);
                    }
                }
                Instruction::Phi { incoming, .. } => {
                    for (op, _) in incoming {
                        if let Operand::Value(v) = op {
                            ok.insert(v.0);
                        }
                    }
                }
                Instruction::Select {
                    true_val,
                    false_val,
                    ..
                } => {
                    for op in [true_val, false_val] {
                        if let Operand::Value(v) = op {
                            ok.insert(v.0);
                        }
                    }
                }
                _ => {}
            }
            inst.for_each_used_value(|id| {
                if ok.contains(&id) {
                    return;
                }
                // Provenance, not spelling: any mention of a value that may
                // point into a candidate — through casts, copies, phis,
                // selects, or variable-offset GEPs, none of which the old
                // const-GEP root walk could see — rejects it.
                if let Some(ts) = touches.get(&id) {
                    for &a in ts {
                        bad.insert(a);
                    }
                }
            });
        }
    }
    // Terminators: a data-flow mention of the object's address in a
    // terminator (`return a;`) is an escape — the rewrite would delete the
    // alloca out from under the reference, leaving a dangling use the
    // backend refuses to fabricate (found live: `return a;` ICE'd emit.rs
    // before this scan existed). CondBranch/Switch/IndirectBranch value
    // mentions are equally impossible to honor for an object address.
    for block in &func.blocks {
        let mut hits: Vec<u32> = Vec::new();
        block.terminator.for_each_used_value(|id| {
            if let Some(ts) = touches.get(&id) {
                hits.extend(ts.iter().copied());
            }
        });
        for a in hits {
            bad.insert(a);
        }
    }

    // ---- collect every sound candidate --------------------------------------
    // Dominators are computed at most once per function, on demand (only
    // when a candidate survives the tiling and read-use gates).
    let mut dom: Option<Vec<usize>> = None;
    let mut ordered: Vec<u32> = allocas.keys().copied().collect();
    ordered.sort_unstable();
    for a in ordered {
        if bad.contains(&a) {
            continue;
        }
        let size = allocas[&a].0;
        let align = allocas[&a].1.max(1);
        let Some(sts) = stores.get(&a) else {
            continue;
        };
        if sts.is_empty() {
            continue;
        }
        // A real READ (load or read-only call) is required: a write-only
        // object promotes into dead .rodata.
        if !read_uses.contains(&a) {
            continue;
        }
        // Exact tiling with no overlap.
        let mut image = vec![0u8; size];
        let mut covered = vec![false; size];
        let mut tiled = true;
        for st in sts {
            let w = st.width as i64;
            if st.offset < 0 || st.offset.saturating_add(w) > size as i64 {
                tiled = false;
                break;
            }
            let Some(bytes) = const_bytes(&st.value, st.width) else {
                tiled = false;
                break;
            };
            for (k, byte) in bytes.into_iter().enumerate() {
                let idx = st.offset as usize + k;
                if covered[idx] {
                    tiled = false;
                    break;
                }
                covered[idx] = true;
                image[idx] = byte;
            }
            if !tiled {
                break;
            }
        }
        if !tiled || covered.iter().any(|c| !*c) {
            continue;
        }
        // Dominance: all stores in one block that dominates every use block.
        let mut site_blocks = store_blocks.get(&a).cloned().unwrap_or_default();
        site_blocks.sort_unstable();
        site_blocks.dedup();
        if site_blocks.len() != 1 {
            continue;
        }
        let store_block = site_blocks[0];
        let dom = dom.get_or_insert_with(|| dominators(func));
        let mut dominated = true;
        for &ub in use_blocks.get(&a).cloned().unwrap_or_default().as_slice() {
            let mut d = ub;
            let mut found = false;
            let mut guard = 0;
            while d != usize::MAX && guard <= func.blocks.len() {
                if d == store_block {
                    found = true;
                    break;
                }
                let next = dom[d];
                if next == usize::MAX || next == d {
                    break;
                }
                d = next;
                guard += 1;
            }
            if !found {
                dominated = false;
                break;
            }
        }
        if !dominated {
            continue;
        }
        out.push((a, size, align, image));
    }
    out
}

/// Apply one audited candidate's rewrite: substitute the address uses with
/// a fresh `GlobalAddr`, and delete the initialization.
fn apply_one(func: &mut IrFunction, a: u32, global_name: &str) {
    let geps = gep_roots(func);
    let mut fresh = func.next_value_id.max(func.max_value_id() + 1);
    let addr = Value(fresh);
    fresh += 1;
    func.next_value_id = fresh;

    // Delete the initialization stores and the alloca while the alloca id is
    // still meaningful.
    for block in &mut func.blocks {
        block.instructions.retain(|inst| match inst {
            Instruction::Store { ptr, .. } => addr_of(ptr.0, a, &geps).is_none(),
            Instruction::Alloca { dest, .. } => dest.0 != a,
            _ => true,
        });
    }
    // Substitute every remaining address use. The audited positions are
    // exactly: Load pointers, GEP bases, direct-call arguments, and the
    // address-dataflow derivation instructions (Cast/Copy sources, Phi
    // arms, Select arms) — the IR's pointers are untyped `IrType::Ptr`, so
    // the GlobalAddr value substitutes type-exactly through every hop, and
    // the entry-block insertion dominates every use.
    for block in &mut func.blocks {
        for inst in &mut block.instructions {
            match inst {
                Instruction::Load { ptr, .. } => {
                    if ptr.0 == a {
                        *ptr = addr;
                    }
                }
                Instruction::GetElementPtr { base, .. } => {
                    if base.0 == a {
                        *base = addr;
                    }
                }
                Instruction::Call { info, .. } => {
                    for arg in &mut info.args {
                        if let Operand::Value(v) = arg {
                            if v.0 == a {
                                *v = addr;
                            }
                        }
                    }
                }
                Instruction::Cast { src, .. } => {
                    if let Operand::Value(v) = src {
                        if v.0 == a {
                            *v = addr;
                        }
                    }
                }
                Instruction::Copy { src, .. } => {
                    if let Operand::Value(v) = src {
                        if v.0 == a {
                            *v = addr;
                        }
                    }
                }
                Instruction::Phi { incoming, .. } => {
                    for (op, _) in incoming.iter_mut() {
                        if let Operand::Value(v) = op {
                            if v.0 == a {
                                *v = addr;
                            }
                        }
                    }
                }
                Instruction::Select {
                    true_val,
                    false_val,
                    ..
                } => {
                    for op in [true_val, false_val] {
                        if let Operand::Value(v) = op {
                            if v.0 == a {
                                *v = addr;
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }
    // Emit the GlobalAddr at the head of the entry block.
    if let Some(entry) = func.blocks.first_mut() {
        entry.instructions.insert(
            0,
            Instruction::GlobalAddr {
                dest: addr,
                name: global_name.to_string(),
            },
        );
    }
}

/// Immediate dominators per block index (usize::MAX for unreachable).
fn dominators(func: &IrFunction) -> Vec<usize> {
    let label_map = crate::ir::analysis::build_label_map(func);
    let (preds, succs) = crate::ir::analysis::build_cfg(func, &label_map);
    crate::ir::analysis::compute_dominators(func.blocks.len(), &preds, &succs)
}

pub(crate) fn run(module: &mut IrModule) -> usize {
    // Phase A (immutable): audit every function against the whole module.
    // The callee-proof cache is shared across functions — the proof is a
    // pure function of (callee, argument index) on the module snapshot.
    let mut proof_cache: FxHashMap<(String, usize), bool> = FxHashMap::default();
    let mut plans: Vec<(usize, Vec<(u32, usize, usize, Vec<u8>)>)> = Vec::new();
    for (fi, f) in module.functions.iter().enumerate() {
        if f.is_declaration {
            continue;
        }
        let cands = audit_candidates(f, &module.functions, &mut proof_cache);
        if !cands.is_empty() {
            plans.push((fi, cands));
        }
    }
    if plans.is_empty() {
        return 0;
    }
    // (No debug environment knob: the pass-pipeline environment-read
    // budget is a ratchet that must never grow, and the audits this knob
    // once printed are now direct unit tests plus the structural gate.)
    // Phase B (mutable): apply the rewrites and materialize the globals.
    // Fresh `.LCA_n` names are chosen by PROBING the set of occupied
    // global names: a count-based suffix can collide with sparse
    // pre-existing labels (e.g. an asm label spelling `.LCA_2` while
    // `.LCA_0` and `.LCA_4` also exist), and a second pass invocation on
    // the same module must not reuse a name it created earlier.
    let mut used_names: FxHashSet<String> = module.globals.iter().map(|g| g.name.clone()).collect();
    let mut changes = 0usize;
    let mut new_globals: Vec<IrGlobal> = Vec::new();
    for (fi, cands) in plans {
        for (a, size, align, image) in cands {
            let mut n = 0;
            let name = loop {
                let candidate = format!(".LCA_{}", n);
                if !used_names.contains(&candidate) {
                    break candidate;
                }
                n += 1;
            };
            used_names.insert(name.clone());
            new_globals.push(IrGlobal {
                name: name.clone(),
                ty: IrType::U8,
                size,
                // The promoted object keeps the alloca's alignment: an
                // int[4] array promised its consumers 4-byte-aligned
                // storage, and .rodata placement at align 1 would silently
                // turn every aligned load unaligned.
                align,
                init: GlobalInit::Array(image.iter().map(|&b| IrConst::I8(b as i8)).collect()),
                is_static: true,
                is_const: true,
                is_extern: false,
                is_common: false,
                section: None,
                is_weak: false,
                visibility: None,
                has_explicit_align: false,
                is_used: true,
                is_thread_local: false,
            });
            apply_one(&mut module.functions[fi], a, &name);
            changes += 1;
        }
    }
    module.globals.extend(new_globals);
    changes
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::reexports::BlockId;

    fn block(
        label: u32,
        insts: Vec<Instruction>,
        term: Terminator,
    ) -> crate::ir::reexports::BasicBlock {
        crate::ir::reexports::BasicBlock {
            label: BlockId(label),
            instructions: insts,
            terminator: term,
            source_spans: Vec::new(),
        }
    }

    fn mk_module(fns: Vec<IrFunction>, globals: Vec<IrGlobal>) -> IrModule {
        let mut m = IrModule::new();
        m.functions = fns;
        m.globals = globals;
        m
    }

    /// The repository SSA/CFG validator over the transformed module: the
    /// promoted caller must stay well-formed (GlobalAddr dominance, no
    /// dangling uses of the deleted alloca).
    fn assert_verified(m: &IrModule, stage: &str) {
        crate::passes::verify::verify_after_pass(m, stage);
    }

    /// A caller whose 16-byte array is fully initialized by constants and
    /// read by a static load-only callee: must promote.
    #[test]
    fn static_load_only_callee_promotes() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.is_static = true;
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(2),
                    ptr: Value(1),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(2)))),
        )];
        reader.next_value_id = 3;

        let mut caller = IrFunction::new("caller".to_string(), IrType::I32, vec![], false);
        caller.blocks = vec![block(
            0,
            vec![
                Instruction::Alloca {
                    dest: Value(1),
                    size: 16,
                    align: 1,
                    ty: IrType::U8,
                    volatile: false,
                    semantic_volatile: false,
                },
                Instruction::GetElementPtr {
                    dest: Value(2),
                    base: Value(1),
                    offset: Operand::Const(IrConst::I64(0)),
                    ty: IrType::U8,
                },
                Instruction::Store {
                    val: Operand::Const(IrConst::I32(0x04030201)),
                    ptr: Value(2),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Const(IrConst::I32(0)))),
        )];
        // (Single-store partial init on purpose: the tiling gate rejects
        // it; the positive-control full tiling lives in the next test.)
        caller.next_value_id = 3;
        let mut m = mk_module(vec![caller, reader], vec![]);
        let n = run(&mut m);
        assert_eq!(n, 0, "partial tiling must not promote");
    }

    /// A weak read-only body licenses nothing: the linked definition may be
    /// a strong override that writes through the parameter.
    #[test]
    fn weak_callee_rejects() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.is_weak = true;
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(2),
                    ptr: Value(1),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(2)))),
        )];
        reader.next_value_id = 3;
        // Direct proof call: the weak body must fail even though its body
        // only loads.
        let mut cache = FxHashMap::default();
        let fns = vec![reader];
        assert!(!callee_readonly_through(&fns, "reader", 0, &mut cache));
        // And the cache agrees on a second ask.
        assert!(!callee_readonly_through(&fns, "reader", 0, &mut cache));
    }

    /// A duplicated ParamRef for the same index rejects (fail closed rather
    /// than auditing whichever one was seen last).
    #[test]
    fn duplicated_param_ref_rejects() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::ParamRef {
                    dest: Value(4),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(2),
                    ptr: Value(1),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(2)))),
        )];
        reader.next_value_id = 5;
        let mut cache = FxHashMap::default();
        let fns = vec![reader];
        assert!(!callee_readonly_through(&fns, "reader", 0, &mut cache));
    }

    /// `BuiltinSetjmp` writes its jump buffer through `args[0]` with no
    /// `dest_ptr` and no `writes_memory_via_args` membership: the callee
    /// proof must reject a pointer that reaches it.
    #[test]
    fn builtin_setjmp_argument_rejects() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Intrinsic {
                    dest: None,
                    dest_ptr: None,
                    op: IntrinsicOp::BuiltinSetjmp,
                    args: vec![Operand::Value(Value(1))],
                },
            ],
            Terminator::Return(Some(Operand::Const(IrConst::I32(0)))),
        )];
        reader.next_value_id = 2;
        let mut cache = FxHashMap::default();
        let fns = vec![reader];
        assert!(
            !callee_readonly_through(&fns, "reader", 0, &mut cache),
            "setjmp's buffer argument is a memory write"
        );
    }

    /// A pointer-to-integer cast fed to a scalar pure intrinsic (CRC32)
    /// OBSERVES the address: promotion would change the computed value, so
    /// the proof must reject. Casting back to a pointer (re-entry) must
    /// still be allowed.
    #[test]
    fn pointer_identity_observation_rejects() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I64, vec![], false);
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                // ptr -> int: the address value becomes observable.
                Instruction::Cast {
                    dest: Value(2),
                    src: Operand::Value(Value(1)),
                    from_ty: IrType::Ptr,
                    to_ty: IrType::I64,
                },
                // int -> ptr on a COPY of the same integer: re-entry is fine
                // when nothing else consumed the integer — so build the
                // observation on a separate chain.
                Instruction::Cast {
                    dest: Value(6),
                    src: Operand::Value(Value(1)),
                    from_ty: IrType::Ptr,
                    to_ty: IrType::I64,
                },
                Instruction::Cast {
                    dest: Value(7),
                    src: Operand::Value(Value(6)),
                    from_ty: IrType::I64,
                    to_ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(8),
                    ptr: Value(7),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
                Instruction::Intrinsic {
                    dest: Some(Value(3)),
                    dest_ptr: None,
                    op: IntrinsicOp::Crc32_64,
                    args: vec![Operand::Value(Value(2))],
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(3)))),
        )];
        reader.next_value_id = 9;
        let mut cache = FxHashMap::default();
        let fns = vec![reader];
        assert!(
            !callee_readonly_through(&fns, "reader", 0, &mut cache),
            "crc32 of the pointer's integer value observes the address"
        );

        // Without the crc32 consumption (the int only flows back into a
        // pointer), the proof holds: re-entry is a legitimate round trip.
        let mut roundtrip = IrFunction::new("roundtrip".to_string(), IrType::I32, vec![], false);
        roundtrip.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Cast {
                    dest: Value(2),
                    src: Operand::Value(Value(1)),
                    from_ty: IrType::Ptr,
                    to_ty: IrType::I64,
                },
                Instruction::Cast {
                    dest: Value(3),
                    src: Operand::Value(Value(2)),
                    from_ty: IrType::I64,
                    to_ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(4),
                    ptr: Value(3),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(4)))),
        )];
        roundtrip.next_value_id = 5;
        let mut cache = FxHashMap::default();
        let fns = vec![roundtrip];
        assert!(
            callee_readonly_through(&fns, "roundtrip", 0, &mut cache),
            "a pure ptr->int->ptr round trip observes nothing"
        );
    }

    /// A load through a caller-side COPY of the address (the derivation
    /// chains the rewrite now supports) must promote — the copy's source is
    /// substituted with the GlobalAddr.
    #[test]
    fn caller_side_copy_derivation_promotes() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.is_static = true;
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(2),
                    ptr: Value(1),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(2)))),
        )];
        reader.next_value_id = 3;

        let mut caller = IrFunction::new("caller".to_string(), IrType::I32, vec![], false);
        let mut stores = Vec::new();
        let mut next = 3;
        for i in 0..4usize {
            stores.push(Instruction::GetElementPtr {
                dest: Value(next),
                base: Value(1),
                offset: Operand::Const(IrConst::I64((i * 4) as i64)),
                ty: IrType::U8,
            });
            stores.push(Instruction::Store {
                val: Operand::Const(IrConst::I32(i as i32)),
                ptr: Value(next),
                ty: IrType::I32,
                volatile: false,
                seg_override: crate::common::types::AddressSpace::Default,
            });
            next += 1;
        }
        // const int *p = a; reader(p);
        stores.push(Instruction::Copy {
            dest: Value(next),
            src: Operand::Value(Value(1)),
        });
        let p = Value(next);
        next += 1;
        caller.blocks = vec![block(
            0,
            {
                let mut v = vec![Instruction::Alloca {
                    dest: Value(1),
                    size: 16,
                    align: 1,
                    ty: IrType::U8,
                    volatile: false,
                    semantic_volatile: false,
                }];
                v.extend(stores);
                v.push(Instruction::Call {
                    func: "reader".to_string(),
                    info: crate::ir::reexports::CallInfo {
                        args: vec![Operand::Value(p)],
                        ..crate::ir::reexports::CallInfo::default()
                    },
                });
                v
            },
            Terminator::Return(Some(Operand::Const(IrConst::I32(0)))),
        )];
        caller.next_value_id = next;
        let mut m = mk_module(vec![caller, reader], vec![]);
        let n = run(&mut m);
        assert_verified(&m, "constarr:copy-derivation");
        assert_eq!(n, 1, "the copy-derived read promotes");
        // The caller's remaining instructions reference the GlobalAddr, and
        // no instruction references the deleted alloca id 1.
        let caller = &m.functions[0];
        let mut has_global = false;
        for b in &caller.blocks {
            for inst in &b.instructions {
                if let Instruction::GlobalAddr { .. } = inst {
                    has_global = true;
                }
                inst.for_each_used_value(|id| {
                    assert_ne!(id, 1, "deleted alloca still referenced");
                });
            }
        }
        assert!(has_global, "the GlobalAddr is materialized");
    }

    /// A write-only object (no load, no read-only call) must NOT promote:
    /// it would become permanent dead .rodata.
    #[test]
    fn write_only_object_does_not_promote() {
        let mut caller = IrFunction::new("caller".to_string(), IrType::I32, vec![], false);
        let mut insts = vec![Instruction::Alloca {
            dest: Value(1),
            size: 4,
            align: 1,
            ty: IrType::U8,
            volatile: false,
            semantic_volatile: false,
        }];
        insts.push(Instruction::Store {
            val: Operand::Const(IrConst::I32(7)),
            ptr: Value(1),
            ty: IrType::I32,
            volatile: false,
            seg_override: crate::common::types::AddressSpace::Default,
        });
        caller.blocks = vec![block(
            0,
            insts,
            Terminator::Return(Some(Operand::Const(IrConst::I32(0)))),
        )];
        caller.next_value_id = 2;
        let mut m = mk_module(vec![caller], vec![]);
        let n = run(&mut m);
        assert_eq!(n, 0, "write-only object stays an alloca");
        assert!(m.globals.is_empty(), "no .rodata materialized");
    }

    /// Sparse pre-existing `.LCA_` names cannot collide with generated ones:
    /// with `.LCA_0` and `.LCA_2` already present, the first fresh name is
    /// `.LCA_1` (count-based generation would emit `.LCA_2` again).
    #[test]
    fn sparse_preexisting_lca_names_do_not_collide() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.is_static = true;
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(2),
                    ptr: Value(1),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(2)))),
        )];
        reader.next_value_id = 3;

        let mut caller = IrFunction::new("caller".to_string(), IrType::I32, vec![], false);
        let mut insts = vec![Instruction::Alloca {
            dest: Value(1),
            size: 4,
            align: 1,
            ty: IrType::U8,
            volatile: false,
            semantic_volatile: false,
        }];
        insts.push(Instruction::Store {
            val: Operand::Const(IrConst::I32(7)),
            ptr: Value(1),
            ty: IrType::I32,
            volatile: false,
            seg_override: crate::common::types::AddressSpace::Default,
        });
        insts.push(Instruction::Call {
            func: "reader".to_string(),
            info: crate::ir::reexports::CallInfo {
                args: vec![Operand::Value(Value(1))],
                ..crate::ir::reexports::CallInfo::default()
            },
        });
        caller.blocks = vec![block(
            0,
            insts,
            Terminator::Return(Some(Operand::Const(IrConst::I32(0)))),
        )];
        caller.next_value_id = 2;

        let pre = |name: &str| IrGlobal {
            name: name.to_string(),
            ty: IrType::U8,
            size: 1,
            align: 1,
            init: GlobalInit::Array(vec![IrConst::I8(0)]),
            is_static: true,
            is_const: true,
            is_extern: false,
            is_common: false,
            section: None,
            is_weak: false,
            visibility: None,
            has_explicit_align: false,
            is_used: true,
            is_thread_local: false,
        };
        let mut m = mk_module(vec![caller, reader], vec![pre(".LCA_0"), pre(".LCA_2")]);
        let n = run(&mut m);
        assert_verified(&m, "constarr:sparse-names");
        assert_eq!(n, 1);
        let names: Vec<&str> = m.globals.iter().map(|g| g.name.as_str()).collect();
        assert!(names.contains(&".LCA_1"), "names: {:?}", names);
        // No duplicates.
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), names.len(), "no duplicate globals");
    }

    /// A store through a variable-offset GEP of the array rejects the
    /// candidate (the shipped P0: the runtime store landed in .rodata).
    #[test]
    fn variable_offset_store_rejects() {
        let mut reader = IrFunction::new("reader".to_string(), IrType::I32, vec![], false);
        reader.is_static = true;
        reader.blocks = vec![block(
            0,
            vec![
                Instruction::ParamRef {
                    dest: Value(1),
                    param_idx: 0,
                    ty: IrType::Ptr,
                },
                Instruction::Load {
                    dest: Value(2),
                    ptr: Value(1),
                    ty: IrType::I32,
                    volatile: false,
                    seg_override: crate::common::types::AddressSpace::Default,
                },
            ],
            Terminator::Return(Some(Operand::Value(Value(2)))),
        )];
        reader.next_value_id = 3;

        let mut caller = IrFunction::new("caller".to_string(), IrType::I32, vec![], false);
        let mut insts = vec![
            Instruction::ParamRef {
                dest: Value(9),
                param_idx: 0,
                ty: IrType::I32,
            },
            Instruction::Alloca {
                dest: Value(1),
                size: 16,
                align: 1,
                ty: IrType::U8,
                volatile: false,
                semantic_volatile: false,
            },
        ];
        // Constant tiling first.
        for i in 0..4usize {
            insts.push(Instruction::GetElementPtr {
                dest: Value(10 + i as u32),
                base: Value(1),
                offset: Operand::Const(IrConst::I64((i * 4) as i64)),
                ty: IrType::U8,
            });
            insts.push(Instruction::Store {
                val: Operand::Const(IrConst::I32(i as i32)),
                ptr: Value(10 + i as u32),
                ty: IrType::I32,
                volatile: false,
                seg_override: crate::common::types::AddressSpace::Default,
            });
        }
        // Then the variable-offset runtime store.
        insts.push(Instruction::GetElementPtr {
            dest: Value(20),
            base: Value(1),
            offset: Operand::Value(Value(9)),
            ty: IrType::U8,
        });
        insts.push(Instruction::Store {
            val: Operand::Value(Value(9)),
            ptr: Value(20),
            ty: IrType::I32,
            volatile: false,
            seg_override: crate::common::types::AddressSpace::Default,
        });
        insts.push(Instruction::Call {
            func: "reader".to_string(),
            info: crate::ir::reexports::CallInfo {
                args: vec![Operand::Value(Value(1))],
                ..crate::ir::reexports::CallInfo::default()
            },
        });
        caller.blocks = vec![block(
            0,
            insts,
            Terminator::Return(Some(Operand::Const(IrConst::I32(0)))),
        )];
        caller.next_value_id = 21;
        let mut m = mk_module(vec![caller, reader], vec![]);
        let n = run(&mut m);
        assert_eq!(n, 0, "the variable-offset store rejects promotion");
    }
}
