mod alu;
mod asm_emitter;
mod atomics;
mod calls;
mod casts;
mod comparison;
pub(crate) mod emit;
mod float_ops;
mod globals;
mod i128_ops;
mod inline_asm;
mod intrinsics;
mod magic_div;
mod memory;
mod nested_fn;
pub(crate) mod peephole;
mod prologue;
mod returns;
mod variadic;
