#!/usr/bin/env python3
"""Generate isolated i686 addressing boundary cases (GNU as is the oracle).

No bytes or expected diagnostics are hard-coded: scripts/asmdiff.py compares
one object per case against GAS, including .text, relocations and symbols.
Order and input set are deterministic; the output is checked in so hosted CI
runs the exact same matrix. Run from the repository root, without flags.
"""
from pathlib import Path

OUT = Path("tests/asm-diff/i686/merged-pr630-mode-matrix.casefile")
MODES = ("code16", "code16gcc", "code32")
ADDRESSES = ("(%bx)", "(%bp)", "(%bp,%si)", "(%eax)", "(%esp)")
# EVEX tuple64 boundary, disp16 vs disp32, zero/bp special encoding,
# positive and negative disp8*N limits (signed byte [-128,127]).
EVEX_DISPS = (-8192, -1024, -129, -128, -64, -8, -1, 0, 1, 8,
              16, 63, 64, 127, 128, 255, 256, 8128, 8192)
VEX_DISPS = (-129, -128, -1, 0, 1, 127, 128, 256)
XOP_DISPS = (-129, -1, 0, 1, 127, 128)
BCST_DISPS = (-516, 0, 4, 512)


def main() -> None:
    groups = []

    def add(kind: str, mode: str, address: str, disp: int, line: str) -> None:
        tag = address.replace("%", "").replace("(", "").replace(")", "")
        tag = tag.replace(",", "_").replace("-", "neg")
        d = f"neg{abs(disp)}" if disp < 0 else str(disp)
        groups.append(
            f";;; pr630_matrix_{kind}_{mode}_{tag}_{d}\n"
            f".text\n.{mode}\n{line}\n"
        )

    for mode in MODES:
        for address in ADDRESSES:
            for disp in EVEX_DISPS:
                add("evex64", mode, address, disp,
                    f"vmovdqu8 {disp}{address},%zmm1")
        # Differing opcode families force VEX2/C4, XOP, and EVEX broadcast
        # tuple4 through the same address bridge (not just vmovdqu8).
        for address in ("(%bp,%si)", "(%eax)"):
            for disp in VEX_DISPS:
                add("vex", mode, address, disp,
                    f"vaddps {disp}{address},%xmm2,%xmm1")
            for disp in XOP_DISPS:
                add("xop", mode, address, disp,
                    f"vpcmov %xmm1,{disp}{address},%xmm2,%xmm3")
            for disp in BCST_DISPS:
                add("evexbcst", mode, address, disp,
                    f"vpaddd {disp}{address}{{1to16}},%zmm1,%zmm2")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# Generated by engineering/evidence/2026-09-26-pr630-review/"
        "generate_mode_matrix.py; isolated GAS 2.47 oracle cases.\n\n"
        + "\n".join(groups)
    )
    print(f"generated {len(groups)} deterministic i686 address cases: {OUT}")


if __name__ == "__main__":
    main()
