#!/bin/bash
# For each pass kill switch, check whether disabling that pass makes the build
# agree with gcc again. A switch that restores correctness names a pass whose
# handling of the input is implicated (or names a pass that merely hides the
# real culprit by reshaping the code — treat a hit as a direction, not a proof).
#
# Usage: killswitch_bisect.sh <file.c>          # default compiler
#        LCCC_BIN=/path/to/lccc killswitch_bisect.sh <file.c>
#        SPLIT=0 killswitch_bisect.sh <file.c>  # do not force the aggregate split
#
# History: the first version of this script read its switch list from
# /tmp/killsw.txt (generated by hand) AND prefixed every harvested name with
# `CCC_`, while the names it harvested already begin with `CCC_NO_`. It
# therefore exported `CCC_CCC_NO_X` for variables nothing reads, and when /tmp
# was wiped between turns the loop iterated over nothing. Both failure modes
# print "no FIXED-BY" — which was reported as the finding "no kill switch
# restores agreement", and it sent the investigation to the register allocator
# while the actual defect sat in a peephole that `CCC_NO_PEEPHOLE_PHASE1=1`
# disables in one step. Never let a sweep print an empty result: the list is
# now generated here, and an empty list is fatal.
set -u
BIN=${LCCC_BIN:-/home/user/lccc/target/fastbuild/lccc}
SRC=${1:?usage: killswitch_bisect.sh <file.c>}
SPLIT=${SPLIT:-1}
TREE=$(CDPATH= cd -- "$(dirname -- "$BIN")/../.." && pwd)
[ -d "$TREE/src" ] || TREE=/home/user/lccc

# 1. Harvest the switch names from the source, not from a scratch file.
LIST=$(grep -rhoE '\bCCC_NO_[A-Z0-9_]+\b' "$TREE/src" 2>/dev/null | sort -u)
N=$(printf '%s\n' "$LIST" | grep -c . || true)
if [ "${N:-0}" -lt 20 ]; then
    echo "FATAL: harvested only $N switches from $TREE/src — the tree is wrong" >&2
    exit 1
fi
echo "switches tried: $N"

gcc -O2 "$SRC" -o /tmp/ks_gcc 2>/dev/null || { echo "gcc build failed" >&2; exit 1; }
REF=$(/tmp/ks_gcc 2>&1); RC=$?
SPLITENV=()
[ "$SPLIT" = 1 ] && SPLITENV=(CCC_AGGREGATE_SPLIT=1)
env -u CCC_NO_AGGREGATE_SPLIT "${SPLITENV[@]}" "$BIN" -O2 "$SRC" -o /tmp/ks_bad 2>/dev/null
BAD=$(/tmp/ks_bad 2>&1)
echo "ref(rc=$RC): $REF"
echo "on        : $BAD"
if [ "$BAD" = "$REF" ]; then
    echo "no mismatch with all passes on — nothing to bisect"
    exit 0
fi

# 2. Run each switch in an environment scrubbed of ambient CCC_*/LCCC_* state,
#    with the harvested name verbatim (no `CCC_` prefixing).
CLEAN=(PATH="$PATH" HOME="$HOME")
hits=0
for k in $LIST; do
    if env -i "${CLEAN[@]}" "${SPLITENV[@]}" "$k=1" "$BIN" -O2 "$SRC" -o /tmp/ks_t 2>/dev/null; then
        o=$(/tmp/ks_t 2>&1)
        if [ "$o" = "$REF" ]; then
            echo "FIXED-BY  $k"
            hits=$((hits + 1))
        fi
    fi
done
echo "switches restoring agreement: $hits / $N"
[ "$hits" -eq 0 ] && echo "NOTE: no single switch hides it — the defect survives every pass toggle."
exit 0
