#!/usr/bin/env python3
"""Deterministic 100K-function ICF scale corpus.

Regenerates the scale corpus the ICF bound work (D4) validates against:
100 objects x 1000 functions each, plus a 200-link reference chain and a
main that roots a spread of functions. All generation is seeded, so the
corpus is byte-identical across runs and machines (given the same gcc).

Shapes (deliberately mixed to stress every ICF stage):
  * 90 x const-return functions cycling 10 constants (10 big fold groups),
  * 10 x same-file call edges (relocation-target class refinement),
  * one 200-link cross-function chain (multi-pass peeling; exercises the
    32-pass cap without changing the exact outcome: singletons either way),
  * main roots ~200 spread functions plus the chain head.

Usage:
  scripts/icf_scale_corpus.py gen <dir>        # generate + compile (.o files)
  scripts/icf_scale_corpus.py link <lccc> <dir> <out> [--icf=safe|all]
      # link with the given lccc binary, print sha/size/wall time

Link with --no-gc-sections: the point is ICF scale, so every function must
reach the refinement (with GC only the ~200 roots would survive and the
benchmark would measure nothing).
"""
import hashlib
import os
import subprocess
import sys
import time

NFILES = 100
NFUNC = 1000
CHAIN = 200
SEED = 0x1CF


def gen_unit(fi):
    """One translation unit's C source (deterministic in fi)."""
    lines = ["/* generated by icf_scale_corpus.py: unit %d */" % fi]
    nxt = (fi + 1) % NFILES
    # Forward declarations for the cross-TU call edges.
    for j in range(NFUNC):
        lines.append("int f%d_%d(void);" % (nxt, j))
    # Static leaf + 10 static callers: same bytes, same local target, so the
    # callers fold within the unit (exercises local-target comparison).
    lines.append("static int leaf%d(void){ return %d; }" % (fi, 42 + fi))
    for k in range(10):
        lines.append("static int s%d_%d(void){ return leaf%d(); }" % (fi, k, fi))
    for j in range(NFUNC):
        if j % 10 == 9:
            # Cross-TU call edge: the callee is in another object, so gcc
            # cannot inline it away (same-TU edges into const callees
            # collapse to const bodies and the reloc shape vanishes).
            lines.append("int f%d_%d(void){ return f%d_%d() + %d; }"
                         % (fi, j, nxt, j, j % 3))
        else:
            # 10 fold shapes cycling with the function index.
            lines.append("int f%d_%d(void){ return %d; }" % (fi, j, (j + fi) % 10))
    return "\n".join(lines) + "\n"


def gen_chain():
    # The links are STATIC: global callees would key every link's skeleton
    # by callee name (199 singleton buckets, zero refinement), while local
    # callees share one bucket and peel one link per pass — the multi-pass
    # shape the pass cap exists for. Only the head is global (main's entry).
    lines = ["/* generated by icf_scale_corpus.py: 200-link chain */"]
    for j in range(1, CHAIN):
        lines.append("static int c%d(void);" % j)
    lines.append("int c0(void){ return c1(); }")
    for j in range(1, CHAIN):
        if j + 1 < CHAIN:
            lines.append("static int c%d(void){ return c%d(); }" % (j, j + 1))
        else:
            lines.append("static int c%d(void){ extern int chain_ext; return chain_ext; }" % j)
    return "\n".join(lines) + "\n"


def gen_main():
    lines = ["/* generated by icf_scale_corpus.py: main */",
             "#include <stdio.h>",
             "int chain_ext = 7;"]
    for fi in range(NFILES):
        lines.append("int f%d_%d(void);" % (fi, (fi * 37) % NFUNC))
        lines.append("int f%d_%d(void);" % (fi, (fi * 37 + 500) % NFUNC))
    lines.append("int c0(void);")
    lines.append("int main(void){")
    lines.append("  long s = c0();")
    for fi in range(NFILES):
        lines.append("  s += f%d_%d();" % (fi, (fi * 37) % NFUNC))
        lines.append("  s += f%d_%d();" % (fi, (fi * 37 + 500) % NFUNC))
    lines.append('  printf("%ld\\n", s);')
    lines.append("  return 0;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def cmd_gen(outdir):
    os.makedirs(outdir, exist_ok=True)
    units = [("u%d.c" % fi, gen_unit(fi)) for fi in range(NFILES)]
    units.append(("chain.c", gen_chain()))
    units.append(("main.c", gen_main()))
    for name, src in units:
        with open(os.path.join(outdir, name), "w") as f:
            f.write(src)
    # Compile serially: -O1 -j2 mandate, and gcc on 1000-func units is fast.
    # chain.c keeps interprocedural propagation off: at -O2 gcc would clone
    # the tail load through all 200 links (making them byte-identical
    # readers instead of a chain) and the multi-pass peeling shape would
    # silently vanish from the corpus.
    for name, _ in units:
        src = os.path.join(outdir, name)
        obj = src[:-2] + ".o"
        flags = ["gcc", "-O2", "-ffunction-sections", "-fdata-sections",
                 "-c", src, "-o", obj]
        if name == "chain.c":
            flags[1:1] = ["-fno-ipa-cp", "-fno-ipa-icf", "-fno-inline"]
        r = subprocess.run(flags, capture_output=True, text=True)
        if r.returncode != 0:
            print("compile failed for %s:\n%s" % (name, r.stderr))
            sys.exit(1)
    nobjs = len([n for n in os.listdir(outdir) if n.endswith(".o")])
    print("corpus: %d objects in %s" % (nobjs, outdir))


def cmd_link(lccc, outdir, out, icf):
    objs = sorted(os.path.join(outdir, n) for n in os.listdir(outdir)
                  if n.endswith(".o"))
    t0 = time.time()
    r = subprocess.run([lccc, "-O1", "-o", out,
                        "-Wl,--no-gc-sections", "-Wl,--icf=%s" % icf] + objs,
                       capture_output=True, text=True)
    dt = time.time() - t0
    if r.returncode != 0:
        print("link failed:\n%s" % r.stderr[-3000:])
        sys.exit(1)
    with open(out, "rb") as f:
        digest = hashlib.sha256(f.read()).hexdigest()[:12]
    size = os.path.getsize(out)
    print("link: sha=%s size=%d wall=%.2fs icf=%s" % (digest, size, dt, icf))


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 1
    if argv[1] == "gen" and len(argv) == 3:
        cmd_gen(argv[2])
    elif argv[1] == "link" and len(argv) in (5, 6):
        icf = "safe"
        if len(argv) == 6:
            if not argv[5].startswith("--icf="):
                print("want --icf=safe|all")
                return 1
            icf = argv[5][6:]
        cmd_link(argv[2], argv[3], argv[4], icf)
    else:
        print(__doc__)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
