#!/usr/bin/env bash
# ============================================================================
# LCCC session snapshot for the Vite/web-app harness ("Kontinuität v2").
#
# ROOT CAUSE of lost snapshots: in this harness the ONLY artefact that reaches
# the user is the single-file Vite build (dist/index.html produced by
# vite-plugin-singlefile) plus the sandbox source tree.  Files written under
# /home/user/artifacts or the repo worktree are invisible to the user and are
# wiped with the sandbox.
#
# Therefore every validated improvement is materialised INSIDE the web
# bundle's source tree so `npm run build` inlines it into the delivered HTML:
#
#   $SANDBOX/public/patches/ms178-1.patch           (static copy, canonical)
#   $SANDBOX/public/patches/ms178-1.<tag>.patch     (per-snapshot copy)
#   $SANDBOX/src/generated/patch.ts                 (patch as a TS string,
#                                                    bundled into index.html)
#   $SANDBOX/src/generated/ledger.json              (machine-readable ledger)
#   $SANDBOX/src/generated/docs.json                (follow-up docs, bundled)
#
# The web app offers the patch as a Blob download, shows its SHA-256, the
# ledger and the docs, so the deliverable survives even if only the HTML
# survives.  Writes are atomic (tmp + rename); the patch is verified to apply
# cleanly to the recorded upstream base before it is published.
#
# Usage:  scripts/lccc-harness-snapshot.sh "<slug>" "<one-line description>"
# Env:    LCCC_REPO (default /home/user/lccc)   LCCC_SANDBOX (default
#         /home/user/sandbox)   LCCC_BASE_REF (upstream commit; recorded once)
#         LCCC_SNAPSHOT_DOCS (space-separated repo-relative docs to bundle)
# ============================================================================
set -euo pipefail

REPO=${LCCC_REPO:-/home/user/lccc}
SANDBOX=${LCCC_SANDBOX:-/home/user/sandbox}
GEN="$SANDBOX/src/generated"
PUB="$SANDBOX/public/patches"
LEDGER="$GEN/ledger.json"
BASE_REF_FILE="$GEN/.base_ref"
DOCS=${LCCC_SNAPSHOT_DOCS:-"docs/I686_ALU_AUDIT.md docs/FOLLOWUP_I686_ALU.md"}

slug=${1:-snapshot}
desc=${2:-"session snapshot"}
stamp=$(date -u +%Y%m%dT%H%M%SZ)

mkdir -p "$GEN/docs" "$PUB"
cd "$REPO"

if [[ -f "$BASE_REF_FILE" ]]; then
  BASE=$(cat "$BASE_REF_FILE")
else
  BASE=${LCCC_BASE_REF:-$(git rev-parse HEAD)}
  printf '%s\n' "$BASE" > "$BASE_REF_FILE"
fi

# Commit pending work (deterministic identity).
if ! git diff --quiet || ! git diff --cached --quiet || \
   [[ -n "$(git ls-files --others --exclude-standard)" ]]; then
  git add -A
  git -c user.name='LCCC Agent' -c user.email='agent@lccc.local' \
      commit -q -m "$slug: $desc" || true
fi
HEAD_SHA=$(git rev-parse HEAD)

atomic_write() { local dest=$1 tmp="$1.tmp.$$"; cat > "$tmp"; sync -f "$tmp" 2>/dev/null || true; mv -f "$tmp" "$dest"; }

# Sequence number from the ledger.
seq=1
if [[ -f "$LEDGER" ]]; then
  seq=$(( $(python3 -c "import json;print(len(json.load(open('$LEDGER'))['snapshots']))") + 1 ))
fi
tag=$(printf 'S%02d-%s' "$seq" "$slug")

# 1. The patch (base..HEAD, binary-safe).
patch_tmp=$(mktemp)
git diff --binary --no-color "$BASE" HEAD > "$patch_tmp"
bytes=$(wc -c < "$patch_tmp")
sha=$(sha256sum "$patch_tmp" | cut -d' ' -f1)
atomic_write "$PUB/ms178-1.patch" < "$patch_tmp"
atomic_write "$PUB/ms178-1.$tag.patch" < "$patch_tmp"

# 2. Verify it applies to the base.
verdict="EMPTY"
if [[ "$bytes" -gt 0 ]]; then
  tmpd=$(mktemp -d)
  if git worktree add -q --detach "$tmpd" "$BASE" 2>/dev/null; then
    if git -C "$tmpd" apply --check "$patch_tmp" 2>/dev/null; then verdict="APPLIES-CLEAN"; else verdict="APPLY-FAILED"; fi
    git worktree remove --force "$tmpd" 2>/dev/null || true
  else
    verdict="UNVERIFIED"
  fi
  rm -rf "$tmpd"
fi

# 3. Embed as TypeScript (bundled into the single-file HTML).
python3 - "$patch_tmp" "$GEN/patch.ts" "$tag" "$sha" "$bytes" "$BASE" "$HEAD_SHA" "$stamp" "$verdict" <<'PY'
import json, os, sys
src, dst, tag, sha, bytes_, base, head, stamp, verdict = sys.argv[1:]
text = open(src, encoding='utf-8', errors='surrogateescape').read()
meta = dict(tag=tag, sha256=sha, bytes=int(bytes_), base=base, head=head, stamp=stamp, verdict=verdict)
body = ("// AUTO-GENERATED by scripts/lccc-harness-snapshot.sh — do not edit.\n"
        "export const PATCH_META = " + json.dumps(meta, indent=2) + " as const;\n"
        "export const PATCH_TEXT: string = " + json.dumps(text) + ";\n")
tmp = dst + ".tmp"
open(tmp, "w", encoding="utf-8", errors="surrogateescape").write(body)
os.replace(tmp, dst)
PY

# 4. Ledger (JSON, appended).
python3 - "$LEDGER" "$seq" "$stamp" "$tag" "$desc" "$bytes" "$sha" "$verdict" "$BASE" "$HEAD_SHA" "$(git diff --shortstat "$BASE" HEAD | sed 's/^ *//')" <<'PY'
import json, os, sys
path, seq, stamp, tag, desc, bytes_, sha, verdict, base, head, stat = sys.argv[1:]
led = {"base": base, "snapshots": []}
if os.path.exists(path):
    led = json.load(open(path))
led["base"] = base
led["snapshots"].append(dict(seq=int(seq), utc=stamp, tag=tag, description=desc,
                             bytes=int(bytes_), sha256=sha, verdict=verdict, head=head, diffstat=stat))
tmp = path + ".tmp"
json.dump(led, open(tmp, "w"), indent=2); os.replace(tmp, path)
PY

# 5. Bundle docs that must reach the user.
for d in $DOCS; do
  [[ -f "$d" ]] && cp -f "$d" "$GEN/docs/$(basename "$d")"
done
( cd "$GEN/docs" && python3 -c "
import json,glob,os
print(json.dumps({os.path.basename(f): open(f).read() for f in sorted(glob.glob('*.md'))}))" ) | atomic_write "$GEN/docs.json"

rm -f "$patch_tmp"

# 6. Rebuild the single-file web bundle so dist/index.html carries this
#    snapshot even if the session dies before the harness's final build.
if [[ -f "$SANDBOX/package.json" ]]; then
  ( cd "$SANDBOX" && npm run build >/dev/null 2>&1 ) && web="dist rebuilt" || web="WARN: web build failed"
else
  web="no sandbox package.json"
fi
sync 2>/dev/null || true
echo "SNAPSHOT $tag"
echo "  base       : $BASE"
echo "  head       : $HEAD_SHA"
echo "  patch      : $PUB/ms178-1.patch ($bytes bytes, sha256 $sha) [$verdict]"
echo "  embedded   : $GEN/patch.ts ($web)"
