#!/usr/bin/env bash
# ============================================================================
# LCCC session snapshot ("Kontinuität") — harness-wipe-resistant autosave.
#
# The execution harness may wipe storage or terminate this script at arbitrary
# points.  A snapshot therefore has two invariants:
#
#   * source is committed before it is published; and
#   * every published file is built and verified off-path, then installed with
#     an atomic rename.  A kill can preserve an older complete snapshot or
#     leave a disposable .tmp file, but cannot publish a truncated patch,
#     archive, bundle, or ledger.
#
# The canonical deliverable /home/user/ms178-1.patch is refreshed on every
# successful call.  The snapshot also records a reviewable format-patch series
# and ledger under /home/user/artifacts, the git bundle (the one artifact that
# cannot be re-derived from the checkout — it carries the full history for
# arena_session_restore.sh's .git recovery — so it MUST live in the persisted
# zone) under /home/user/artifacts as well, and the source tarball (fully
# derivable, ~9 MB) in the snapshot-excluded bulk zone.
#
# Usage:  ./lccc-snapshot.sh "<slug>" "<one-line description>"
# Env:    LCCC_REPO, LCCC_ARTIFACTS, LCCC_DELIVERABLE
#         LCCC_CI_STAMP — ci_local.sh pass stamp (default target/ci_local.pass);
#                         the snapshot refuses a tree without a matching
#                         mode=full one (--fast alone is not CI-equivalent).
#         LCCC_SNAPSHOT_ALLOW_PARTIAL=1 — accept a --fast/--slow stamp for an
#                         interim autosave (ledger: *-PARTIAL-NOT-DELIVERABLE).
#         LCCC_SNAPSHOT_UNGATED=1 — emergency pre-wipe save without that proof
#                         (ledger ci_gate=UNGATED; never a delivery candidate).
#         LCCC_BASE_REF — explicit upstream base for a rebase/new session.
#                         When set, it atomically supersedes artifacts/.base_ref
#                         after ancestry validation.
# ============================================================================
set -euo pipefail

# The checkout this script lives in.  LCCC_REPO still overrides, but the default
# must work from any clone: the deliverable is produced by running this script
# from the tree it describes.
REPO=${LCCC_REPO:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}
ART=${LCCC_ARTIFACTS:-/home/user/artifacts}
# Derived bulk artifacts (the 8–9 MB source tarball and the repo-sized git
# bundle) are regenerated by every run and fully derivable from the checkout,
# so they land in the snapshot-EXCLUDED zone by default: the persisted
# workspace stays far below the ~128 MB / 10k-file snapshot caps (the S62
# harness-choke lesson), while `LCCC_BULK_ARTIFACTS` still overrides for a
# run that must publish them.
BULK=${LCCC_BULK_ARTIFACTS:-/home/user/target/artifacts}
mkdir -p "$BULK"
BASE_REF_FILE="$ART/.base_ref"
DELIVERABLE=${LCCC_DELIVERABLE:-/home/user/ms178-1.patch}
LEDGER="$ART/SNAPSHOT_LEDGER.md"

slug=${1:-snapshot}
desc=${2:-"session snapshot"}
stamp=$(date -u +%Y%m%dT%H%M%SZ)
seq_file="$ART/.seq"

if [[ ! $slug =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
  printf 'invalid snapshot slug %q (use letters, digits, dot, underscore, dash)\n' "$slug" >&2
  exit 2
fi
desc=${desc//$'\n'/ }
desc=${desc//$'\r'/ }

mkdir -p "$ART" "$(dirname "$DELIVERABLE")"
cd "$REPO"

atomic_write() {  # atomic_write <destination>; content arrives on stdin
  local dest=$1 tmp
  mkdir -p "$(dirname "$dest")"
  tmp=$(mktemp "${dest}.tmp.XXXXXX")
  if ! cat > "$tmp"; then
    rm -f "$tmp"
    return 1
  fi
  sync -f "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$dest"
  # Published artifacts are data files, not secrets: mktemp's 0600 must not
  # leak onto them (an owner-only deliverable breaks downstream readers).
  chmod 644 "$dest"
}

atomic_copy() {  # atomic_copy <source> <destination>
  local source=$1 dest=$2 tmp
  mkdir -p "$(dirname "$dest")"
  tmp=$(mktemp "${dest}.tmp.XXXXXX")
  if ! cp -f -- "$source" "$tmp"; then
    rm -f "$tmp"
    return 1
  fi
  sync -f "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$dest"
  chmod 644 "$dest"
}

previous_base=""
if [[ -f "$BASE_REF_FILE" ]]; then
  previous_base=$(tr -d '[:space:]' < "$BASE_REF_FILE")
fi
if [[ -n ${LCCC_BASE_REF:-} ]]; then
  BASE=$(git rev-parse --verify "${LCCC_BASE_REF}^{commit}")
elif [[ -n $previous_base ]]; then
  BASE=$(git rev-parse --verify "${previous_base}^{commit}")
else
  # On a first snapshot, capture HEAD *before* committing pending work so the
  # generated patch contains that work rather than being empty.
  BASE=$(git rev-parse HEAD)
fi

# Refuse to commit a snapshot whose staged diff deletes tracked files or
# changes file modes, unless LCCC_SNAPSHOT_ALLOW_STRUCTURAL=1.
#
# Both are near-invisible accidents in this harness, and both have shipped:
#
#   * The harness wipes storage between turns and the restore strips exec
#     bits, so a following `git add -A` stages 100755 -> 100644 for every
#     script in the tree. Seventy-six mode-only hunks once made a 521-line
#     patch weigh 104 KiB.
#   * Five tracked files match patterns in this repo's own .gitignore
#     (`core.*` covers src/backend/{x86,i686}/assembler/encoder/core.rs;
#     `test_*` covers tests/integration/test_progressive.py and
#     tests/test_ivsr_indexed{.c,_before.s}). Once a wipe removes them,
#     `git add -A` stages the deletion and -- because ignored paths are
#     omitted from `git status` -- the tree reports CLEAN, so the loss stays
#     invisible until the published patch deletes two backend encoders.
#
# A published patch that deletes tracked files or drops exec bits is a
# restoration accident here, not an edit, so fail closed and keep the
# previous snapshot. Set LCCC_SNAPSHOT_ALLOW_STRUCTURAL=1 for a snapshot that
# genuinely removes or re-modes files.
# Refuse to publish against a stale base.
#
# `.base_ref` pins the upstream commit the deliverable is diffed from. After a
# rebase onto a newer upstream main it still names the OLD main, so the patch
# silently absorbs every upstream commit in between: a 6-file / 38 KiB series
# once published as 21 files / 143 KiB because PR #438's aggregate-SROA work
# was diffed as if it were ours. Nothing in the pipeline noticed, because the
# extra content is a legitimate diff -- it is just not this series.
#
# The invariant is cheap: the recorded base must be the merge base of HEAD and
# the fetched upstream main. When `origin/main` is unavailable (offline) the
# check is skipped rather than guessed. LCCC_SNAPSHOT_ALLOW_STALE_BASE=1
# overrides for a deliberate historical base.
snapshot_guard_base_is_merge_base() {
  if [[ ${LCCC_SNAPSHOT_ALLOW_STALE_BASE:-0} == 1 ]]; then
    return 0
  fi
  local upstream mb
  upstream=$(git rev-parse --verify --quiet origin/main) || return 0
  mb=$(git merge-base "$HEAD_SHA" "$upstream" 2>/dev/null) || return 0
  if [[ $mb != "$BASE" ]]; then
    printf 'snapshot guard: base %s is not the merge base of HEAD and origin/main (%s)\n' \
      "${BASE:0:12}" "${mb:0:12}" >&2
    printf '  The deliverable would absorb upstream commits as if they were ours.\n' >&2
    printf '  After a rebase, re-anchor:  printf %%s\\n %s > %s\n' "$mb" "$BASE_REF_FILE" >&2
    return 1
  fi
  return 0
}

snapshot_guard_staged_diff() {
  if [[ ${LCCC_SNAPSHOT_ALLOW_STRUCTURAL:-0} == 1 ]]; then
    echo "snapshot guard: structural changes explicitly allowed" >&2
    return 0
  fi
  local deleted modes bad=0
  deleted=$(git diff --cached --name-status | awk '$1 ~ /^D/ { print "    " $2 }')
  modes=$(git diff --cached --summary | grep 'mode change' | sed 's/^/    /')
  if [[ -n $deleted ]]; then
    echo "snapshot guard: staged diff DELETES tracked files:" >&2
    printf '%s\n' "$deleted" >&2
    bad=1
  fi
  if [[ -n $modes ]]; then
    if [[ ${LCCC_SNAPSHOT_ALLOW_MODES:-0} == 1 ]]; then
      # Deliberate mode fixes (e.g. making documented entry points
      # executable) are legitimate patch CONTENT.  They must be requested
      # explicitly and stay visible in the snapshot log; an accidental
      # wipe-induced mode change has no reason to set this flag.
      echo "snapshot guard: staged diff changes file modes (ALLOWED by" >&2
      echo "  LCCC_SNAPSHOT_ALLOW_MODES=1 — deliberate mode fixes):" >&2
      printf '%s\n' "$modes" >&2
    else
      echo "snapshot guard: staged diff changes file modes:" >&2
      printf '%s\n' "$modes" | head -5 >&2
      echo "    ($(printf '%s\n' "$modes" | wc -l) in total)" >&2
      echo "  If these are DELIBERATE mode fixes (e.g. chmod +x on documented" >&2
      echo "  entry points), re-run with LCCC_SNAPSHOT_ALLOW_MODES=1." >&2
      bad=1
    fi
  fi
  if ((bad)); then
    cat >&2 <<'MSG'
  This is almost always a harness wipe: restore the paths and their modes
  before snapshotting, e.g.
      git checkout <upstream-main> -- <paths>
      git ls-files -s <paths>            # confirm 100755 where expected
  Note that ignored-but-tracked paths never reappear via `git add -A`.
MSG
    return 1
  fi
  return 0
}

# ---- CI-mirror gate -----------------------------------------------------------
# A snapshot is a delivery candidate, so it must carry proof that EXACTLY this
# tree passed the local CI mirror (S20 shipped a red CI because ci_local.sh was
# skipped). ci_local.sh writes the git tree hash of the worktree it tested --
# re-checked at the end, so an edit during the run voids it -- and we compare
# it with the tree `git add -A` is about to commit. Running the 30+ minute
# mirror here instead would defeat the point of a fast, wipe-resistant
# autosave. LCCC_SNAPSHOT_UNGATED=1 exists for emergency pre-wipe saves only
# and is recorded as such in the ledger.
CI_STAMP=${LCCC_CI_STAMP:-$REPO/target/ci_local.pass}
tree_now=$(bash "$REPO/scripts/worktree_tree.sh" "$REPO") ||
  { echo "unable to hash the worktree" >&2; exit 1; }
# Read only an existing stamp: under `set -euo pipefail` a failing sed in the
# substitution would abort the script without the explanation below.
stamp_tree='' stamp_mode='' stamp_os=''
if [[ -r $CI_STAMP ]]; then
  stamp_tree=$(sed -n 's/^tree=//p' "$CI_STAMP" | head -1)
  stamp_mode=$(sed -n 's/^mode=//p' "$CI_STAMP" | head -1)
  stamp_os=$(sed -n 's/^os=//p' "$CI_STAMP" | head -1)
fi
if [[ -n $stamp_tree && $stamp_tree == "$tree_now" && $stamp_mode == full ]]; then
  # Recorded, not enforced: GitHub's ubuntu-latest moves (24.04 -> 26.04 on
  # 2026-10-19) and not every host can run the chroot mirror. A non-Ubuntu
  # userland is shown in the ledger so a reviewer knows what was mirrored.
  ci_gate="ci_local-full-PASS@${stamp_os:-unknown-os}"
  if [[ ${stamp_os:-} != ubuntu-* ]]; then
    echo "WARNING: gates ran on ${stamp_os:-an unrecorded userland}, not the Ubuntu" \
         "runner's; scripts/ci_ubuntu_chroot.sh -- bash scripts/ci_local.sh mirrors it." >&2
  fi
elif [[ -n $stamp_tree && $stamp_tree == "$tree_now" &&
        ${LCCC_SNAPSHOT_ALLOW_PARTIAL:-0} == 1 ]]; then
  # A --fast (or --slow) stamp covers only part of what GitHub runs: S24 went
  # red on PR #638 in check_peephole_whitespace.sh, a gate --fast skips, after
  # this script had accepted its fast stamp. Partial stamps are therefore only
  # an interim autosave, labelled as such in the ledger, never a delivery.
  ci_gate="ci_local-${stamp_mode:-unknown}-PARTIAL-NOT-DELIVERABLE"
  echo "WARNING: tree $tree_now has only a mode=${stamp_mode:-unknown} stamp;" \
       "recorded as $ci_gate." >&2
elif [[ ${LCCC_SNAPSHOT_UNGATED:-0} == 1 ]]; then
  ci_gate="UNGATED"
  echo "WARNING: snapshot of tree $tree_now WITHOUT a matching ci_local.sh pass;" \
       "recorded as UNGATED -- not a delivery candidate." >&2
else
  cat >&2 <<MSG
refusing to snapshot: tree $tree_now has no matching FULL ci_local.sh pass
  stamp: $CI_STAMP (tree=${stamp_tree:-none}, mode=${stamp_mode:-none})
GitHub CI runs every gate, so only mode=full is delivery-grade. Run
./scripts/ci_local.sh (full), or --fast and then --slow on this exact tree.
Interim autosave with a partial stamp: LCCC_SNAPSHOT_ALLOW_PARTIAL=1.
Emergency pre-wipe save without any stamp: LCCC_SNAPSHOT_UNGATED=1.
MSG
  exit 3
fi

if ! git diff --quiet || ! git diff --cached --quiet || \
   [[ -n "$(git ls-files --others --exclude-standard)" ]]; then
  git add -A
  snapshot_guard_staged_diff || exit 1
  git -c user.name='LCCC Agent' -c user.email='agent@lccc.local' \
      commit -m "$slug: $desc"
fi

HEAD_SHA=$(git rev-parse HEAD)
if ! git merge-base --is-ancestor "$BASE" "$HEAD_SHA"; then
  printf 'snapshot base %s is not an ancestor of HEAD %s\n' "$BASE" "$HEAD_SHA" >&2
  exit 1
fi
snapshot_guard_base_is_merge_base || exit 1

# Publish a requested/new base atomically only after it has been verified
# against the committed snapshot head. The per-entry ledger note below makes a
# base re-anchor auditable without rewriting historic entries.
if [[ $previous_base != "$BASE" ]]; then
  printf '%s\n' "$BASE" | atomic_write "$BASE_REF_FILE"
fi
base_note=""
if [[ -n $previous_base && $previous_base != "$BASE" ]]; then
  base_note="re-anchored from $previous_base to $BASE"
elif [[ -z $previous_base ]]; then
  base_note="initialized at $BASE"
fi

if [[ -f "$seq_file" ]]; then
  current_seq=$(tr -d '[:space:]' < "$seq_file")
  [[ $current_seq =~ ^[0-9]+$ ]] || { echo "invalid snapshot sequence: $current_seq" >&2; exit 1; }
else
  current_seq=0
fi
seq=$((current_seq + 1))
tag=$(printf 'S%02d-%s' "$seq" "$slug")

# ---- 1. Produce and verify the patch before publishing any new snapshot -----
patch_tmp=$(mktemp "$ART/.ms178-1.${tag}.patch.tmp.XXXXXX")
if [[ "$HEAD_SHA" != "$BASE" ]]; then
  git diff --binary --no-color "$BASE" "$HEAD_SHA" > "$patch_tmp"
else
  : > "$patch_tmp"
fi
bytes=$(wc -c < "$patch_tmp")
verdict="EMPTY"
if [[ "$bytes" -gt 0 ]]; then
  verify_worktree=$(mktemp -d "${TMPDIR:-/tmp}/lccc-snapshot-verify.XXXXXX")
  cleanup_verify() {
    git -C "$REPO" worktree remove --force "$verify_worktree" >/dev/null 2>&1 || true
    rm -rf "$verify_worktree"
  }
  if ! git -C "$REPO" worktree add --detach "$verify_worktree" "$BASE" >/dev/null; then
    rm -f "$patch_tmp"
    echo "unable to create verification worktree" >&2
    exit 1
  fi
  if ! git -C "$verify_worktree" apply --check "$patch_tmp"; then
    cleanup_verify
    rm -f "$patch_tmp"
    echo "generated patch does not apply cleanly to its recorded base" >&2
    exit 1
  fi
  cleanup_verify
  verdict="APPLIES-CLEAN"
fi

# ---- 2. Materialize the three patch copies atomically ------------------------
atomic_copy "$patch_tmp" "$DELIVERABLE"
atomic_copy "$patch_tmp" "$ART/ms178-1.patch"
atomic_copy "$patch_tmp" "$ART/ms178-1.${tag}.patch"
patch_sha=$(sha256sum "$patch_tmp" | awk '{print $1}')
rm -f "$patch_tmp"

# ---- 3. Per-commit series (reviewable history) -------------------------------
series_tmp=$(mktemp -d "$ART/.series.tmp.XXXXXX")
if ! git format-patch -q -o "$series_tmp" "$BASE..$HEAD_SHA" >/dev/null; then
  rm -rf "$series_tmp"
  echo "git format-patch failed; preserving prior series" >&2
  exit 1
fi
series_backup="$ART/.series.previous.${tag}"
rm -rf "$series_backup"
if [[ -e "$ART/series" ]]; then
  mv "$ART/series" "$series_backup"
fi
if ! mv "$series_tmp" "$ART/series"; then
  [[ -e "$series_backup" ]] && mv "$series_backup" "$ART/series" || true
  echo "unable to publish patch series; prior series restored when possible" >&2
  exit 1
fi
rm -rf "$series_backup"

# ---- 4. Full source tarball (fallback if patch application breaks) -----------
# mktemp IN THE DESTINATION DIRECTORY: the rename below must stay within one
# filesystem to be atomic (audit F8 — a cross-fs mv is copy+unlink, and a kill
# mid-copy would publish a truncated tarball, breaking the header invariant).
tar_tmp=$(mktemp "$BULK/.lccc-src.tar.gz.tmp.XXXXXX")
if ! tar --exclude=.git --exclude=target --exclude=node_modules \
    --exclude=__pycache__ --exclude='*.pyc' \
    -czf "$tar_tmp" -C "$(dirname "$REPO")" "$(basename "$REPO")"; then
  rm -f "$tar_tmp"
  echo "source tarball creation failed; preserving prior archive" >&2
  exit 1
fi
[[ -s "$tar_tmp" ]] || { rm -f "$tar_tmp"; echo "source tarball is empty" >&2; exit 1; }
sync -f "$tar_tmp" 2>/dev/null || true
mv -f "$tar_tmp" "$BULK/lccc-src.tar.gz"
tar_sha=$(sha256sum "$BULK/lccc-src.tar.gz" | awk '{print $1}')

# ---- 5. Git bundle (the .git-recovery artifact — DURABLE zone) ----------------
# arena_session_restore.sh rebuilds a wiped .git by cloning
# /home/user/artifacts/lccc.bundle; publishing it into the snapshot-excluded
# bulk zone would make recovery impossible exactly when it is needed (audit
# F8 path-agreement law).  The bundle is one ~1-9 MB file — far below the
# workspace caps.
#
# A bundle cut from a shallow clone (the restore path's --depth 200
# upstream clone) names prerequisites the receiver lacks: `git bundle
# verify` still reports "okay", but cloning it fails with "remote did not
# send all necessary objects" (the S03 bundle: the bundle-recovery path
# silently dead for two sessions).  Unshallow first when the network
# allows — silently and with a timeout, so an offline snapshot neither
# hangs nor warns — then PROVE the artifact by test-cloning it.  A bundle
# that cannot be cloned is flagged in the ledger (bundle_clone=FAIL),
# never silently published; the patch, series and tarball above are the
# load-bearing artifacts, so a convenience-artifact failure warns rather
# than blocking the wipe protection this script exists to provide.
if [[ -f .git/shallow ]]; then
  timeout 180 git fetch --unshallow -q 2>/dev/null || true
fi
bundle_tmp=$(mktemp "$ART/.lccc.bundle.tmp.XXXXXX")
if ! git bundle create "$bundle_tmp" --all; then
  rm -f "$bundle_tmp"
  echo "git bundle creation failed; preserving prior bundle" >&2
  exit 1
fi
[[ -s "$bundle_tmp" ]] || { rm -f "$bundle_tmp"; echo "git bundle is empty" >&2; exit 1; }
bundle_clone=OK
bundle_verify_dir=$(mktemp -d "${TMPDIR:-/tmp}/lccc-bundle-verify.XXXXXX")
if git clone -q "$bundle_tmp" "$bundle_verify_dir" 2>/dev/null; then
  rm -rf "$bundle_verify_dir"
else
  rm -rf "$bundle_verify_dir"
  bundle_clone=FAIL
  echo "WARNING: published bundle fails test-clone; restore will fall back" \
       "to an upstream clone (bundle_clone=FAIL in the ledger)." >&2
fi
sync -f "$bundle_tmp" 2>/dev/null || true
mv -f "$bundle_tmp" "$ART/lccc.bundle"
bundle_sha=$(sha256sum "$ART/lccc.bundle" | awk '{print $1}')

# ---- 6. Atomically extend the ledger ------------------------------------------
ledger_tmp=$(mktemp "$ART/.SNAPSHOT_LEDGER.md.tmp.XXXXXX")
if [[ -f "$LEDGER" ]]; then
  cat "$LEDGER" > "$ledger_tmp"
else
  {
    echo "# LCCC Snapshot Ledger"
    echo
    echo "Initial base (upstream): \`$BASE\`"
    echo
    echo "| # | UTC | Tag | Description | Cumulative diffstat |"
    echo "|---|-----|-----|-------------|---------------------|"
  } > "$ledger_tmp"
fi
if [[ -n $base_note ]]; then
  printf '\n<!-- %s: %s -->\n' "$tag" "$base_note" >> "$ledger_tmp"
fi
files=$(git diff --stat "$BASE" "$HEAD_SHA" | tail -1 | sed 's/^ *//')
printf '| %d | %s | `%s` | %s | %s |\n' \
  "$seq" "$stamp" "$tag" "$desc" "${files:-none}" >> "$ledger_tmp"
printf '<!-- base=%s patch_sha256=%s tar_sha256=%s bundle_sha256=%s bundle_clone=%s verdict=%s ci_gate=%s tree=%s -->\n' \
  "$BASE" "$patch_sha" "$tar_sha" "$bundle_sha" "${bundle_clone:-unknown}" "$verdict" "$ci_gate" "$tree_now" >> "$ledger_tmp"
sync -f "$ledger_tmp" 2>/dev/null || true
mv -f "$ledger_tmp" "$LEDGER"

# Advance the sequence only once every independently recoverable artifact and
# the ledger have been published successfully.
printf '%s\n' "$seq" | atomic_write "$seq_file"
sync 2>/dev/null || true

echo "SNAPSHOT $tag"
echo "  base       : $BASE"
echo "  head       : $HEAD_SHA"
echo "  deliverable: $DELIVERABLE ($bytes bytes, sha256 $patch_sha) [$verdict, $ci_gate]"
echo "  source tar : $BULK/lccc-src.tar.gz (sha256 $tar_sha)"
echo "  bundle     : $ART/lccc.bundle (sha256 $bundle_sha)"
echo "  artifacts  : $ART"
echo "  bulk       : $BULK"
