/* GENERATED by gen_string_init_matrix.py -- do not edit. */
#include <stdio.h>
#include <string.h>
#include <uchar.h>
#include <wchar.h>
static unsigned long H = 1469598103u;
static void mix(const char *tag, const void *p, size_t n) { const unsigned char *b = p; unsigned long h = 1469598103u; for (size_t i = 0; i < n; i++) h = (h ^ b[i]) * 16777619u; printf("%s %zu %lx\n", tag, n, h); H ^= h; }
__attribute__((noinline)) static void dirty(void) { volatile unsigned char junk[8192]; memset((unsigned char *)junk, 0x5a, sizeof junk); }
__attribute__((noinline)) static void t_char_1d_short_auto(void) { char v[7] = "ab"; mix("t_char_1d_short_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_short_static(void) { static char v[7] = "ab"; mix("t_char_1d_short_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_exact_auto(void) { char v[2] = "ab"; mix("t_char_1d_exact_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_exact_static(void) { static char v[2] = "ab"; mix("t_char_1d_exact_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_unsized_auto(void) { char v[] = "a\xe9b"; mix("t_char_1d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_unsized_static(void) { static char v[] = "a\xe9b"; mix("t_char_1d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_braced_auto(void) { char v[5] = { "xy" }; mix("t_char_1d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_1d_braced_static(void) { static char v[5] = { "xy" }; mix("t_char_1d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_auto(void) { char v[3][4] = { "ab", "wxyz", "q" }; mix("t_char_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_static(void) { static char v[3][4] = { "ab", "wxyz", "q" }; mix("t_char_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_braced_auto(void) { char v[2][3] = { { "ab" }, { "c" } }; mix("t_char_2d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_braced_static(void) { static char v[2][3] = { { "ab" }, { "c" } }; mix("t_char_2d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_desig_auto(void) { char v[3][3] = { [2] = "hi", [0] = "a" }; mix("t_char_2d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_desig_static(void) { static char v[3][3] = { [2] = "hi", [0] = "a" }; mix("t_char_2d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_unsized_auto(void) { char v[][3] = { "ab", "c" }; mix("t_char_2d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_unsized_static(void) { static char v[][3] = { "ab", "c" }; mix("t_char_2d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_3d_auto(void) { char v[2][2][3] = { { "ab", "c" }, { "d" } }; mix("t_char_3d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_3d_static(void) { static char v[2][2][3] = { { "ab", "c" }, { "d" } }; mix("t_char_3d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_auto(void) { struct { char a[4]; int g; char b[4]; int h; } v = { "ab", 7, "cdef", 9 }; mix("t_char_member_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_static(void) { static struct { char a[4]; int g; char b[4]; int h; } v = { "ab", 7, "cdef", 9 }; mix("t_char_member_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_braced_auto(void) { struct { int g; char a[4]; } v = { 1, { "ab" } }; mix("t_char_member_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_braced_static(void) { static struct { int g; char a[4]; } v = { 1, { "ab" } }; mix("t_char_member_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_desig_auto(void) { struct { int g; char a[4]; int k; } v = { .a = "z", .k = 3 }; mix("t_char_member_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_desig_static(void) { static struct { int g; char a[4]; int k; } v = { .a = "z", .k = 3 }; mix("t_char_member_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_2d_auto(void) { struct { char a[2][4]; int g; } v = { { "ab", "c" }, 5 }; mix("t_char_member_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_2d_static(void) { static struct { char a[2][4]; int g; } v = { { "ab", "c" }, 5 }; mix("t_char_member_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_flat2d_auto(void) { struct { char a[2][4]; int g; } v = { "ab", "c", 5 }; mix("t_char_member_flat2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_flat2d_static(void) { static struct { char a[2][4]; int g; } v = { "ab", "c", 5 }; mix("t_char_member_flat2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_nested_auto(void) { struct { int g; struct { char s[4]; int k; } in; } v = { 1, { "a\xe9", 2 } }; mix("t_char_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_nested_static(void) { static struct { int g; struct { char s[4]; int k; } in; } v = { 1, { "a\xe9", 2 } }; mix("t_char_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_arr_of_struct_auto(void) { struct { char s[4]; int k; } v[2] = { { "ab", 1 }, { "c", 2 } }; mix("t_char_arr_of_struct_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_arr_of_struct_static(void) { static struct { char s[4]; int k; } v[2] = { { "ab", 1 }, { "c", 2 } }; mix("t_char_arr_of_struct_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_arr_of_struct_flat_auto(void) { struct { char s[4]; int k; } v[2] = { "ab", 1, "c", 2 }; mix("t_char_arr_of_struct_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_arr_of_struct_flat_static(void) { static struct { char s[4]; int k; } v[2] = { "ab", 1, "c", 2 }; mix("t_char_arr_of_struct_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_union_auto(void) { union { char s[8]; long long x; } v = { "ab" }; mix("t_char_union_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_union_static(void) { static union { char s[8]; long long x; } v = { "ab" }; mix("t_char_union_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_override_auto(void) { char v[2][4] = { [0] = "abc", [0] = "x", [1] = { 1, 2, 3 }, [1] = "y" }; mix("t_char_2d_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_override_static(void) { static char v[2][4] = { [0] = "abc", [0] = "x", [1] = { 1, 2, 3 }, [1] = "y" }; mix("t_char_2d_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_excess_auto(void) { char v[2][3] = { "ab", "c", "d" }; mix("t_char_2d_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_excess_static(void) { static char v[2][3] = { "ab", "c", "d" }; mix("t_char_2d_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_braced_override_auto(void) { char v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_char_2d_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_2d_braced_override_static(void) { static char v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_char_2d_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_3d_mid_desig_auto(void) { char v[2][2][4] = { [1] = { [1] = "hi" }, [0][1] = "j", "k" }; mix("t_char_3d_mid_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_3d_mid_desig_static(void) { static char v[2][2][4] = { [1] = { [1] = "hi" }, [0][1] = "j", "k" }; mix("t_char_3d_mid_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_desig_chain_auto(void) { struct { int g; char a[3][4]; int k; } v = { .a[1] = "xy", "z", .k = 3 }; mix("t_char_member_desig_chain_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_desig_chain_static(void) { static struct { int g; char a[3][4]; int k; } v = { .a[1] = "xy", "z", .k = 3 }; mix("t_char_member_desig_chain_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_desig_elem_auto(void) { struct { int g; char a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_char_member_desig_elem_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_desig_elem_static(void) { static struct { int g; char a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_char_member_desig_elem_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_2d_desig_rows_auto(void) { struct { char a[3][3]; int k; } v = { { [2] = "p", [0] = { 1 } }, 8 }; mix("t_char_member_2d_desig_rows_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_member_2d_desig_rows_static(void) { static struct { char a[3][3]; int k; } v = { { [2] = "p", [0] = { 1 } }, 8 }; mix("t_char_member_2d_desig_rows_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_union_2d_auto(void) { union { char s[2][3]; long long x[2]; } v = { "a", "bc" }; mix("t_char_union_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char_union_2d_static(void) { static union { char s[2][3]; long long x[2]; } v = { "a", "bc" }; mix("t_char_union_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char_cl_unsized(void) { const char *p = (char[]){ "a\xe9" }; mix("t_char_cl_unsized", p, sizeof((char[]){ "a\xe9" })); }
__attribute__((noinline)) static void t_char_cl_sized(void) { const char *p = (char[5]){ "ab" }; mix("t_char_cl_sized", p, 5 * sizeof(char)); }
__attribute__((noinline)) static void t_char_cl_2d(void) { const char (*p)[3] = (char[2][3]){ "ab", "c" }; mix("t_char_cl_2d", p, 6 * sizeof(char)); }
__attribute__((noinline)) static void t_char_cl_struct(void) { struct cs_char { char a[4]; int g; }; const struct cs_char *p = &(struct cs_char){ "ab", 4 }; mix("t_char_cl_struct", p, sizeof *p); }
static char g_char_2d[2][4] = { "ab", "c\xe9" };
__attribute__((noinline)) static void t_g_char_2d(void) { mix("t_g_char_2d", &g_char_2d, sizeof g_char_2d); }
static struct { char a[3]; char w[3]; } g_char_member = { "ab", "cd" };
__attribute__((noinline)) static void t_g_char_member(void) { mix("t_g_char_member", &g_char_member, sizeof g_char_member); }
static struct { char a[3]; int k; } g_char_arr_struct[2] = { { "ab", 1 }, { "e", 2 } };
__attribute__((noinline)) static void t_g_char_arr_struct(void) { mix("t_g_char_arr_struct", &g_char_arr_struct, sizeof g_char_arr_struct); }
static struct { int n; char s[]; } g_char_fam = { 3, "ab" };
__attribute__((noinline)) static void t_g_char_fam(void) { mix("t_g_char_fam", &g_char_fam, sizeof g_char_fam + 3 * sizeof(char)); }
static struct { const char *p; char a[3]; } g_char_ptrmix = { 0, "ab" };
__attribute__((noinline)) static void t_g_char_ptrmix(void) { mix("t_g_char_ptrmix", &g_char_ptrmix, sizeof g_char_ptrmix); }
static struct { const char *p; char a[2][3]; int k; } g_char_ptrmix_2d = { g_char_2d[1], "ab", "c", 4 };
__attribute__((noinline)) static void t_g_char_ptrmix_2d(void) { mix("t_g_char_ptrmix_2d", g_char_ptrmix_2d.a, sizeof g_char_ptrmix_2d - (size_t)((char *)g_char_ptrmix_2d.a - (char *)&g_char_ptrmix_2d)); if (g_char_ptrmix_2d.p != g_char_2d[1]) puts("t_g_char_ptrmix_2d BADPTR"); }
static struct { const char *p; char a[2][3]; int k; } g_char_ptrmix_2d_desig = { .a[1] = "d", .p = 0, .k = 2 };
__attribute__((noinline)) static void t_g_char_ptrmix_2d_desig(void) { mix("t_g_char_ptrmix_2d_desig", &g_char_ptrmix_2d_desig, sizeof g_char_ptrmix_2d_desig); }
static struct { int n; char s[]; } g_char_fam_big = { 3, "a\xe9" };
__attribute__((noinline)) static void t_g_char_fam_big(void) { mix("t_g_char_fam_big", &g_char_fam_big, sizeof g_char_fam_big + 3 * sizeof(char)); }
static struct { const void *p; struct { char s[4]; char m[2][3]; int k; } in; } g_char_nested_ptr = { 0, { "ab", "c", "d", 5 } };
__attribute__((noinline)) static void t_g_char_nested_ptr(void) { mix("t_g_char_nested_ptr", &g_char_nested_ptr, sizeof g_char_nested_ptr); }
static struct { const void *p; char s[3]; char m[2][2]; } g_char_arr_ptr_flat[2] = { { 0, "a", "b" }, 0, "bc", "d", "e" };
__attribute__((noinline)) static void t_g_char_arr_ptr_flat(void) { mix("t_g_char_arr_ptr_flat", &g_char_arr_ptr_flat, sizeof g_char_arr_ptr_flat); }
static struct { const void *p; struct { int k; char m[3][3]; } in; } g_char_nested_ptr_desig = { .in.m[1] = "x", "yz", .p = 0, .in.k = 7 };
__attribute__((noinline)) static void t_g_char_nested_ptr_desig(void) { mix("t_g_char_nested_ptr_desig", &g_char_nested_ptr_desig, sizeof g_char_nested_ptr_desig); }
static char g_char_3d_desig[2][2][3] = { [1][1] = "z", [0] = { "a", "b" } };
__attribute__((noinline)) static void t_g_char_3d_desig(void) { mix("t_g_char_3d_desig", &g_char_3d_desig, sizeof g_char_3d_desig); }
__attribute__((noinline)) static void t_char16_1d_short_auto(void) { char16_t v[7] = u"ab"; mix("t_char16_1d_short_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_short_static(void) { static char16_t v[7] = u"ab"; mix("t_char16_1d_short_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_exact_auto(void) { char16_t v[2] = u"ab"; mix("t_char16_1d_exact_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_exact_static(void) { static char16_t v[2] = u"ab"; mix("t_char16_1d_exact_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_unsized_auto(void) { char16_t v[] = u"a\U0001F600b"; mix("t_char16_1d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_unsized_static(void) { static char16_t v[] = u"a\U0001F600b"; mix("t_char16_1d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_braced_auto(void) { char16_t v[5] = { u"xy" }; mix("t_char16_1d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_1d_braced_static(void) { static char16_t v[5] = { u"xy" }; mix("t_char16_1d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_auto(void) { char16_t v[3][4] = { u"ab", u"wxyz", u"q" }; mix("t_char16_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_static(void) { static char16_t v[3][4] = { u"ab", u"wxyz", u"q" }; mix("t_char16_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_braced_auto(void) { char16_t v[2][3] = { { u"ab" }, { u"c" } }; mix("t_char16_2d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_braced_static(void) { static char16_t v[2][3] = { { u"ab" }, { u"c" } }; mix("t_char16_2d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_desig_auto(void) { char16_t v[3][3] = { [2] = u"hi", [0] = u"a" }; mix("t_char16_2d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_desig_static(void) { static char16_t v[3][3] = { [2] = u"hi", [0] = u"a" }; mix("t_char16_2d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_unsized_auto(void) { char16_t v[][3] = { u"ab", u"c" }; mix("t_char16_2d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_unsized_static(void) { static char16_t v[][3] = { u"ab", u"c" }; mix("t_char16_2d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_3d_auto(void) { char16_t v[2][2][3] = { { u"ab", u"c" }, { u"d" } }; mix("t_char16_3d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_3d_static(void) { static char16_t v[2][2][3] = { { u"ab", u"c" }, { u"d" } }; mix("t_char16_3d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_auto(void) { struct { char16_t a[4]; int g; char16_t b[4]; int h; } v = { u"ab", 7, u"cdef", 9 }; mix("t_char16_member_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_static(void) { static struct { char16_t a[4]; int g; char16_t b[4]; int h; } v = { u"ab", 7, u"cdef", 9 }; mix("t_char16_member_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_braced_auto(void) { struct { int g; char16_t a[4]; } v = { 1, { u"ab" } }; mix("t_char16_member_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_braced_static(void) { static struct { int g; char16_t a[4]; } v = { 1, { u"ab" } }; mix("t_char16_member_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_desig_auto(void) { struct { int g; char16_t a[4]; int k; } v = { .a = u"z", .k = 3 }; mix("t_char16_member_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_desig_static(void) { static struct { int g; char16_t a[4]; int k; } v = { .a = u"z", .k = 3 }; mix("t_char16_member_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_2d_auto(void) { struct { char16_t a[2][4]; int g; } v = { { u"ab", u"c" }, 5 }; mix("t_char16_member_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_2d_static(void) { static struct { char16_t a[2][4]; int g; } v = { { u"ab", u"c" }, 5 }; mix("t_char16_member_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_flat2d_auto(void) { struct { char16_t a[2][4]; int g; } v = { u"ab", u"c", 5 }; mix("t_char16_member_flat2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_flat2d_static(void) { static struct { char16_t a[2][4]; int g; } v = { u"ab", u"c", 5 }; mix("t_char16_member_flat2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_nested_auto(void) { struct { int g; struct { char16_t s[4]; int k; } in; } v = { 1, { u"a\U0001F600", 2 } }; mix("t_char16_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_nested_static(void) { static struct { int g; struct { char16_t s[4]; int k; } in; } v = { 1, { u"a\U0001F600", 2 } }; mix("t_char16_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_arr_of_struct_auto(void) { struct { char16_t s[4]; int k; } v[2] = { { u"ab", 1 }, { u"c", 2 } }; mix("t_char16_arr_of_struct_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_arr_of_struct_static(void) { static struct { char16_t s[4]; int k; } v[2] = { { u"ab", 1 }, { u"c", 2 } }; mix("t_char16_arr_of_struct_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_arr_of_struct_flat_auto(void) { struct { char16_t s[4]; int k; } v[2] = { u"ab", 1, u"c", 2 }; mix("t_char16_arr_of_struct_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_arr_of_struct_flat_static(void) { static struct { char16_t s[4]; int k; } v[2] = { u"ab", 1, u"c", 2 }; mix("t_char16_arr_of_struct_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_union_auto(void) { union { char16_t s[8]; long long x; } v = { u"ab" }; mix("t_char16_union_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_union_static(void) { static union { char16_t s[8]; long long x; } v = { u"ab" }; mix("t_char16_union_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_override_auto(void) { char16_t v[2][4] = { [0] = u"abc", [0] = u"x", [1] = { 1, 2, 3 }, [1] = u"y" }; mix("t_char16_2d_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_override_static(void) { static char16_t v[2][4] = { [0] = u"abc", [0] = u"x", [1] = { 1, 2, 3 }, [1] = u"y" }; mix("t_char16_2d_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_excess_auto(void) { char16_t v[2][3] = { u"ab", u"c", u"d" }; mix("t_char16_2d_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_excess_static(void) { static char16_t v[2][3] = { u"ab", u"c", u"d" }; mix("t_char16_2d_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_braced_override_auto(void) { char16_t v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_char16_2d_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_2d_braced_override_static(void) { static char16_t v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_char16_2d_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_3d_mid_desig_auto(void) { char16_t v[2][2][4] = { [1] = { [1] = u"hi" }, [0][1] = u"j", u"k" }; mix("t_char16_3d_mid_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_3d_mid_desig_static(void) { static char16_t v[2][2][4] = { [1] = { [1] = u"hi" }, [0][1] = u"j", u"k" }; mix("t_char16_3d_mid_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_desig_chain_auto(void) { struct { int g; char16_t a[3][4]; int k; } v = { .a[1] = u"xy", u"z", .k = 3 }; mix("t_char16_member_desig_chain_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_desig_chain_static(void) { static struct { int g; char16_t a[3][4]; int k; } v = { .a[1] = u"xy", u"z", .k = 3 }; mix("t_char16_member_desig_chain_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_desig_elem_auto(void) { struct { int g; char16_t a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_char16_member_desig_elem_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_desig_elem_static(void) { static struct { int g; char16_t a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_char16_member_desig_elem_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_2d_desig_rows_auto(void) { struct { char16_t a[3][3]; int k; } v = { { [2] = u"p", [0] = { 1 } }, 8 }; mix("t_char16_member_2d_desig_rows_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_member_2d_desig_rows_static(void) { static struct { char16_t a[3][3]; int k; } v = { { [2] = u"p", [0] = { 1 } }, 8 }; mix("t_char16_member_2d_desig_rows_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_union_2d_auto(void) { union { char16_t s[2][3]; long long x[2]; } v = { u"a", u"bc" }; mix("t_char16_union_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_union_2d_static(void) { static union { char16_t s[2][3]; long long x[2]; } v = { u"a", u"bc" }; mix("t_char16_union_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char16_cl_unsized(void) { const char16_t *p = (char16_t[]){ u"a\U0001F600" }; mix("t_char16_cl_unsized", p, sizeof((char16_t[]){ u"a\U0001F600" })); }
__attribute__((noinline)) static void t_char16_cl_sized(void) { const char16_t *p = (char16_t[5]){ u"ab" }; mix("t_char16_cl_sized", p, 5 * sizeof(char16_t)); }
__attribute__((noinline)) static void t_char16_cl_2d(void) { const char16_t (*p)[3] = (char16_t[2][3]){ u"ab", u"c" }; mix("t_char16_cl_2d", p, 6 * sizeof(char16_t)); }
__attribute__((noinline)) static void t_char16_cl_struct(void) { struct cs_char16 { char16_t a[4]; int g; }; const struct cs_char16 *p = &(struct cs_char16){ u"ab", 4 }; mix("t_char16_cl_struct", p, sizeof *p); }
static char16_t g_char16_2d[2][4] = { u"ab", u"c\U0001F600" };
__attribute__((noinline)) static void t_g_char16_2d(void) { mix("t_g_char16_2d", &g_char16_2d, sizeof g_char16_2d); }
static struct { char16_t a[3]; char16_t w[3]; } g_char16_member = { u"ab", u"cd" };
__attribute__((noinline)) static void t_g_char16_member(void) { mix("t_g_char16_member", &g_char16_member, sizeof g_char16_member); }
static struct { char16_t a[3]; int k; } g_char16_arr_struct[2] = { { u"ab", 1 }, { u"e", 2 } };
__attribute__((noinline)) static void t_g_char16_arr_struct(void) { mix("t_g_char16_arr_struct", &g_char16_arr_struct, sizeof g_char16_arr_struct); }
static struct { int n; char16_t s[]; } g_char16_fam = { 3, u"ab" };
__attribute__((noinline)) static void t_g_char16_fam(void) { mix("t_g_char16_fam", &g_char16_fam, sizeof g_char16_fam + 3 * sizeof(char16_t)); }
static struct { const char16_t *p; char16_t a[3]; } g_char16_ptrmix = { 0, u"ab" };
__attribute__((noinline)) static void t_g_char16_ptrmix(void) { mix("t_g_char16_ptrmix", &g_char16_ptrmix, sizeof g_char16_ptrmix); }
static struct { const char16_t *p; char16_t a[2][3]; int k; } g_char16_ptrmix_2d = { g_char16_2d[1], u"ab", u"c", 4 };
__attribute__((noinline)) static void t_g_char16_ptrmix_2d(void) { mix("t_g_char16_ptrmix_2d", g_char16_ptrmix_2d.a, sizeof g_char16_ptrmix_2d - (size_t)((char *)g_char16_ptrmix_2d.a - (char *)&g_char16_ptrmix_2d)); if (g_char16_ptrmix_2d.p != g_char16_2d[1]) puts("t_g_char16_ptrmix_2d BADPTR"); }
static struct { const char16_t *p; char16_t a[2][3]; int k; } g_char16_ptrmix_2d_desig = { .a[1] = u"d", .p = 0, .k = 2 };
__attribute__((noinline)) static void t_g_char16_ptrmix_2d_desig(void) { mix("t_g_char16_ptrmix_2d_desig", &g_char16_ptrmix_2d_desig, sizeof g_char16_ptrmix_2d_desig); }
static struct { int n; char16_t s[]; } g_char16_fam_big = { 3, u"a\U0001F600" };
__attribute__((noinline)) static void t_g_char16_fam_big(void) { mix("t_g_char16_fam_big", &g_char16_fam_big, sizeof g_char16_fam_big + 4 * sizeof(char16_t)); }
static struct { const void *p; struct { char16_t s[4]; char16_t m[2][3]; int k; } in; } g_char16_nested_ptr = { 0, { u"ab", u"c", u"d", 5 } };
__attribute__((noinline)) static void t_g_char16_nested_ptr(void) { mix("t_g_char16_nested_ptr", &g_char16_nested_ptr, sizeof g_char16_nested_ptr); }
static struct { const void *p; char16_t s[3]; char16_t m[2][2]; } g_char16_arr_ptr_flat[2] = { { 0, u"a", u"b" }, 0, u"bc", u"d", u"e" };
__attribute__((noinline)) static void t_g_char16_arr_ptr_flat(void) { mix("t_g_char16_arr_ptr_flat", &g_char16_arr_ptr_flat, sizeof g_char16_arr_ptr_flat); }
static struct { const void *p; struct { int k; char16_t m[3][3]; } in; } g_char16_nested_ptr_desig = { .in.m[1] = u"x", u"yz", .p = 0, .in.k = 7 };
__attribute__((noinline)) static void t_g_char16_nested_ptr_desig(void) { mix("t_g_char16_nested_ptr_desig", &g_char16_nested_ptr_desig, sizeof g_char16_nested_ptr_desig); }
static char16_t g_char16_3d_desig[2][2][3] = { [1][1] = u"z", [0] = { u"a", u"b" } };
__attribute__((noinline)) static void t_g_char16_3d_desig(void) { mix("t_g_char16_3d_desig", &g_char16_3d_desig, sizeof g_char16_3d_desig); }
__attribute__((noinline)) static void t_wchar_1d_short_auto(void) { wchar_t v[7] = L"ab"; mix("t_wchar_1d_short_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_short_static(void) { static wchar_t v[7] = L"ab"; mix("t_wchar_1d_short_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_exact_auto(void) { wchar_t v[2] = L"ab"; mix("t_wchar_1d_exact_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_exact_static(void) { static wchar_t v[2] = L"ab"; mix("t_wchar_1d_exact_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_unsized_auto(void) { wchar_t v[] = L"a\U0001F600b"; mix("t_wchar_1d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_unsized_static(void) { static wchar_t v[] = L"a\U0001F600b"; mix("t_wchar_1d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_braced_auto(void) { wchar_t v[5] = { L"xy" }; mix("t_wchar_1d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_1d_braced_static(void) { static wchar_t v[5] = { L"xy" }; mix("t_wchar_1d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_auto(void) { wchar_t v[3][4] = { L"ab", L"wxyz", L"q" }; mix("t_wchar_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_static(void) { static wchar_t v[3][4] = { L"ab", L"wxyz", L"q" }; mix("t_wchar_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_braced_auto(void) { wchar_t v[2][3] = { { L"ab" }, { L"c" } }; mix("t_wchar_2d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_braced_static(void) { static wchar_t v[2][3] = { { L"ab" }, { L"c" } }; mix("t_wchar_2d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_desig_auto(void) { wchar_t v[3][3] = { [2] = L"hi", [0] = L"a" }; mix("t_wchar_2d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_desig_static(void) { static wchar_t v[3][3] = { [2] = L"hi", [0] = L"a" }; mix("t_wchar_2d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_unsized_auto(void) { wchar_t v[][3] = { L"ab", L"c" }; mix("t_wchar_2d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_unsized_static(void) { static wchar_t v[][3] = { L"ab", L"c" }; mix("t_wchar_2d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_3d_auto(void) { wchar_t v[2][2][3] = { { L"ab", L"c" }, { L"d" } }; mix("t_wchar_3d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_3d_static(void) { static wchar_t v[2][2][3] = { { L"ab", L"c" }, { L"d" } }; mix("t_wchar_3d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_auto(void) { struct { wchar_t a[4]; int g; wchar_t b[4]; int h; } v = { L"ab", 7, L"cdef", 9 }; mix("t_wchar_member_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_static(void) { static struct { wchar_t a[4]; int g; wchar_t b[4]; int h; } v = { L"ab", 7, L"cdef", 9 }; mix("t_wchar_member_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_braced_auto(void) { struct { int g; wchar_t a[4]; } v = { 1, { L"ab" } }; mix("t_wchar_member_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_braced_static(void) { static struct { int g; wchar_t a[4]; } v = { 1, { L"ab" } }; mix("t_wchar_member_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_desig_auto(void) { struct { int g; wchar_t a[4]; int k; } v = { .a = L"z", .k = 3 }; mix("t_wchar_member_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_desig_static(void) { static struct { int g; wchar_t a[4]; int k; } v = { .a = L"z", .k = 3 }; mix("t_wchar_member_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_2d_auto(void) { struct { wchar_t a[2][4]; int g; } v = { { L"ab", L"c" }, 5 }; mix("t_wchar_member_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_2d_static(void) { static struct { wchar_t a[2][4]; int g; } v = { { L"ab", L"c" }, 5 }; mix("t_wchar_member_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_flat2d_auto(void) { struct { wchar_t a[2][4]; int g; } v = { L"ab", L"c", 5 }; mix("t_wchar_member_flat2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_flat2d_static(void) { static struct { wchar_t a[2][4]; int g; } v = { L"ab", L"c", 5 }; mix("t_wchar_member_flat2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_nested_auto(void) { struct { int g; struct { wchar_t s[4]; int k; } in; } v = { 1, { L"a\U0001F600", 2 } }; mix("t_wchar_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_nested_static(void) { static struct { int g; struct { wchar_t s[4]; int k; } in; } v = { 1, { L"a\U0001F600", 2 } }; mix("t_wchar_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_arr_of_struct_auto(void) { struct { wchar_t s[4]; int k; } v[2] = { { L"ab", 1 }, { L"c", 2 } }; mix("t_wchar_arr_of_struct_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_arr_of_struct_static(void) { static struct { wchar_t s[4]; int k; } v[2] = { { L"ab", 1 }, { L"c", 2 } }; mix("t_wchar_arr_of_struct_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_arr_of_struct_flat_auto(void) { struct { wchar_t s[4]; int k; } v[2] = { L"ab", 1, L"c", 2 }; mix("t_wchar_arr_of_struct_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_arr_of_struct_flat_static(void) { static struct { wchar_t s[4]; int k; } v[2] = { L"ab", 1, L"c", 2 }; mix("t_wchar_arr_of_struct_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_union_auto(void) { union { wchar_t s[8]; long long x; } v = { L"ab" }; mix("t_wchar_union_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_union_static(void) { static union { wchar_t s[8]; long long x; } v = { L"ab" }; mix("t_wchar_union_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_override_auto(void) { wchar_t v[2][4] = { [0] = L"abc", [0] = L"x", [1] = { 1, 2, 3 }, [1] = L"y" }; mix("t_wchar_2d_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_override_static(void) { static wchar_t v[2][4] = { [0] = L"abc", [0] = L"x", [1] = { 1, 2, 3 }, [1] = L"y" }; mix("t_wchar_2d_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_excess_auto(void) { wchar_t v[2][3] = { L"ab", L"c", L"d" }; mix("t_wchar_2d_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_excess_static(void) { static wchar_t v[2][3] = { L"ab", L"c", L"d" }; mix("t_wchar_2d_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_braced_override_auto(void) { wchar_t v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_wchar_2d_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_2d_braced_override_static(void) { static wchar_t v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_wchar_2d_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_3d_mid_desig_auto(void) { wchar_t v[2][2][4] = { [1] = { [1] = L"hi" }, [0][1] = L"j", L"k" }; mix("t_wchar_3d_mid_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_3d_mid_desig_static(void) { static wchar_t v[2][2][4] = { [1] = { [1] = L"hi" }, [0][1] = L"j", L"k" }; mix("t_wchar_3d_mid_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_desig_chain_auto(void) { struct { int g; wchar_t a[3][4]; int k; } v = { .a[1] = L"xy", L"z", .k = 3 }; mix("t_wchar_member_desig_chain_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_desig_chain_static(void) { static struct { int g; wchar_t a[3][4]; int k; } v = { .a[1] = L"xy", L"z", .k = 3 }; mix("t_wchar_member_desig_chain_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_desig_elem_auto(void) { struct { int g; wchar_t a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_wchar_member_desig_elem_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_desig_elem_static(void) { static struct { int g; wchar_t a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_wchar_member_desig_elem_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_2d_desig_rows_auto(void) { struct { wchar_t a[3][3]; int k; } v = { { [2] = L"p", [0] = { 1 } }, 8 }; mix("t_wchar_member_2d_desig_rows_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_member_2d_desig_rows_static(void) { static struct { wchar_t a[3][3]; int k; } v = { { [2] = L"p", [0] = { 1 } }, 8 }; mix("t_wchar_member_2d_desig_rows_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_union_2d_auto(void) { union { wchar_t s[2][3]; long long x[2]; } v = { L"a", L"bc" }; mix("t_wchar_union_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_union_2d_static(void) { static union { wchar_t s[2][3]; long long x[2]; } v = { L"a", L"bc" }; mix("t_wchar_union_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_wchar_cl_unsized(void) { const wchar_t *p = (wchar_t[]){ L"a\U0001F600" }; mix("t_wchar_cl_unsized", p, sizeof((wchar_t[]){ L"a\U0001F600" })); }
__attribute__((noinline)) static void t_wchar_cl_sized(void) { const wchar_t *p = (wchar_t[5]){ L"ab" }; mix("t_wchar_cl_sized", p, 5 * sizeof(wchar_t)); }
__attribute__((noinline)) static void t_wchar_cl_2d(void) { const wchar_t (*p)[3] = (wchar_t[2][3]){ L"ab", L"c" }; mix("t_wchar_cl_2d", p, 6 * sizeof(wchar_t)); }
__attribute__((noinline)) static void t_wchar_cl_struct(void) { struct cs_wchar { wchar_t a[4]; int g; }; const struct cs_wchar *p = &(struct cs_wchar){ L"ab", 4 }; mix("t_wchar_cl_struct", p, sizeof *p); }
static wchar_t g_wchar_2d[2][4] = { L"ab", L"c\U0001F600" };
__attribute__((noinline)) static void t_g_wchar_2d(void) { mix("t_g_wchar_2d", &g_wchar_2d, sizeof g_wchar_2d); }
static struct { wchar_t a[3]; wchar_t w[3]; } g_wchar_member = { L"ab", L"cd" };
__attribute__((noinline)) static void t_g_wchar_member(void) { mix("t_g_wchar_member", &g_wchar_member, sizeof g_wchar_member); }
static struct { wchar_t a[3]; int k; } g_wchar_arr_struct[2] = { { L"ab", 1 }, { L"e", 2 } };
__attribute__((noinline)) static void t_g_wchar_arr_struct(void) { mix("t_g_wchar_arr_struct", &g_wchar_arr_struct, sizeof g_wchar_arr_struct); }
static struct { int n; wchar_t s[]; } g_wchar_fam = { 3, L"ab" };
__attribute__((noinline)) static void t_g_wchar_fam(void) { mix("t_g_wchar_fam", &g_wchar_fam, sizeof g_wchar_fam + 3 * sizeof(wchar_t)); }
static struct { const wchar_t *p; wchar_t a[3]; } g_wchar_ptrmix = { 0, L"ab" };
__attribute__((noinline)) static void t_g_wchar_ptrmix(void) { mix("t_g_wchar_ptrmix", &g_wchar_ptrmix, sizeof g_wchar_ptrmix); }
static struct { const wchar_t *p; wchar_t a[2][3]; int k; } g_wchar_ptrmix_2d = { g_wchar_2d[1], L"ab", L"c", 4 };
__attribute__((noinline)) static void t_g_wchar_ptrmix_2d(void) { mix("t_g_wchar_ptrmix_2d", g_wchar_ptrmix_2d.a, sizeof g_wchar_ptrmix_2d - (size_t)((char *)g_wchar_ptrmix_2d.a - (char *)&g_wchar_ptrmix_2d)); if (g_wchar_ptrmix_2d.p != g_wchar_2d[1]) puts("t_g_wchar_ptrmix_2d BADPTR"); }
static struct { const wchar_t *p; wchar_t a[2][3]; int k; } g_wchar_ptrmix_2d_desig = { .a[1] = L"d", .p = 0, .k = 2 };
__attribute__((noinline)) static void t_g_wchar_ptrmix_2d_desig(void) { mix("t_g_wchar_ptrmix_2d_desig", &g_wchar_ptrmix_2d_desig, sizeof g_wchar_ptrmix_2d_desig); }
static struct { int n; wchar_t s[]; } g_wchar_fam_big = { 3, L"a\U0001F600" };
__attribute__((noinline)) static void t_g_wchar_fam_big(void) { mix("t_g_wchar_fam_big", &g_wchar_fam_big, sizeof g_wchar_fam_big + 3 * sizeof(wchar_t)); }
static struct { const void *p; struct { wchar_t s[4]; wchar_t m[2][3]; int k; } in; } g_wchar_nested_ptr = { 0, { L"ab", L"c", L"d", 5 } };
__attribute__((noinline)) static void t_g_wchar_nested_ptr(void) { mix("t_g_wchar_nested_ptr", &g_wchar_nested_ptr, sizeof g_wchar_nested_ptr); }
static struct { const void *p; wchar_t s[3]; wchar_t m[2][2]; } g_wchar_arr_ptr_flat[2] = { { 0, L"a", L"b" }, 0, L"bc", L"d", L"e" };
__attribute__((noinline)) static void t_g_wchar_arr_ptr_flat(void) { mix("t_g_wchar_arr_ptr_flat", &g_wchar_arr_ptr_flat, sizeof g_wchar_arr_ptr_flat); }
static struct { const void *p; struct { int k; wchar_t m[3][3]; } in; } g_wchar_nested_ptr_desig = { .in.m[1] = L"x", L"yz", .p = 0, .in.k = 7 };
__attribute__((noinline)) static void t_g_wchar_nested_ptr_desig(void) { mix("t_g_wchar_nested_ptr_desig", &g_wchar_nested_ptr_desig, sizeof g_wchar_nested_ptr_desig); }
static wchar_t g_wchar_3d_desig[2][2][3] = { [1][1] = L"z", [0] = { L"a", L"b" } };
__attribute__((noinline)) static void t_g_wchar_3d_desig(void) { mix("t_g_wchar_3d_desig", &g_wchar_3d_desig, sizeof g_wchar_3d_desig); }
__attribute__((noinline)) static void t_char32_1d_short_auto(void) { char32_t v[7] = U"ab"; mix("t_char32_1d_short_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_short_static(void) { static char32_t v[7] = U"ab"; mix("t_char32_1d_short_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_exact_auto(void) { char32_t v[2] = U"ab"; mix("t_char32_1d_exact_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_exact_static(void) { static char32_t v[2] = U"ab"; mix("t_char32_1d_exact_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_unsized_auto(void) { char32_t v[] = U"a\U0001F600b"; mix("t_char32_1d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_unsized_static(void) { static char32_t v[] = U"a\U0001F600b"; mix("t_char32_1d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_braced_auto(void) { char32_t v[5] = { U"xy" }; mix("t_char32_1d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_1d_braced_static(void) { static char32_t v[5] = { U"xy" }; mix("t_char32_1d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_auto(void) { char32_t v[3][4] = { U"ab", U"wxyz", U"q" }; mix("t_char32_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_static(void) { static char32_t v[3][4] = { U"ab", U"wxyz", U"q" }; mix("t_char32_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_braced_auto(void) { char32_t v[2][3] = { { U"ab" }, { U"c" } }; mix("t_char32_2d_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_braced_static(void) { static char32_t v[2][3] = { { U"ab" }, { U"c" } }; mix("t_char32_2d_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_desig_auto(void) { char32_t v[3][3] = { [2] = U"hi", [0] = U"a" }; mix("t_char32_2d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_desig_static(void) { static char32_t v[3][3] = { [2] = U"hi", [0] = U"a" }; mix("t_char32_2d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_unsized_auto(void) { char32_t v[][3] = { U"ab", U"c" }; mix("t_char32_2d_unsized_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_unsized_static(void) { static char32_t v[][3] = { U"ab", U"c" }; mix("t_char32_2d_unsized_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_3d_auto(void) { char32_t v[2][2][3] = { { U"ab", U"c" }, { U"d" } }; mix("t_char32_3d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_3d_static(void) { static char32_t v[2][2][3] = { { U"ab", U"c" }, { U"d" } }; mix("t_char32_3d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_auto(void) { struct { char32_t a[4]; int g; char32_t b[4]; int h; } v = { U"ab", 7, U"cdef", 9 }; mix("t_char32_member_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_static(void) { static struct { char32_t a[4]; int g; char32_t b[4]; int h; } v = { U"ab", 7, U"cdef", 9 }; mix("t_char32_member_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_braced_auto(void) { struct { int g; char32_t a[4]; } v = { 1, { U"ab" } }; mix("t_char32_member_braced_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_braced_static(void) { static struct { int g; char32_t a[4]; } v = { 1, { U"ab" } }; mix("t_char32_member_braced_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_desig_auto(void) { struct { int g; char32_t a[4]; int k; } v = { .a = U"z", .k = 3 }; mix("t_char32_member_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_desig_static(void) { static struct { int g; char32_t a[4]; int k; } v = { .a = U"z", .k = 3 }; mix("t_char32_member_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_2d_auto(void) { struct { char32_t a[2][4]; int g; } v = { { U"ab", U"c" }, 5 }; mix("t_char32_member_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_2d_static(void) { static struct { char32_t a[2][4]; int g; } v = { { U"ab", U"c" }, 5 }; mix("t_char32_member_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_flat2d_auto(void) { struct { char32_t a[2][4]; int g; } v = { U"ab", U"c", 5 }; mix("t_char32_member_flat2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_flat2d_static(void) { static struct { char32_t a[2][4]; int g; } v = { U"ab", U"c", 5 }; mix("t_char32_member_flat2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_nested_auto(void) { struct { int g; struct { char32_t s[4]; int k; } in; } v = { 1, { U"a\U0001F600", 2 } }; mix("t_char32_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_nested_static(void) { static struct { int g; struct { char32_t s[4]; int k; } in; } v = { 1, { U"a\U0001F600", 2 } }; mix("t_char32_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_arr_of_struct_auto(void) { struct { char32_t s[4]; int k; } v[2] = { { U"ab", 1 }, { U"c", 2 } }; mix("t_char32_arr_of_struct_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_arr_of_struct_static(void) { static struct { char32_t s[4]; int k; } v[2] = { { U"ab", 1 }, { U"c", 2 } }; mix("t_char32_arr_of_struct_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_arr_of_struct_flat_auto(void) { struct { char32_t s[4]; int k; } v[2] = { U"ab", 1, U"c", 2 }; mix("t_char32_arr_of_struct_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_arr_of_struct_flat_static(void) { static struct { char32_t s[4]; int k; } v[2] = { U"ab", 1, U"c", 2 }; mix("t_char32_arr_of_struct_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_union_auto(void) { union { char32_t s[8]; long long x; } v = { U"ab" }; mix("t_char32_union_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_union_static(void) { static union { char32_t s[8]; long long x; } v = { U"ab" }; mix("t_char32_union_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_override_auto(void) { char32_t v[2][4] = { [0] = U"abc", [0] = U"x", [1] = { 1, 2, 3 }, [1] = U"y" }; mix("t_char32_2d_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_override_static(void) { static char32_t v[2][4] = { [0] = U"abc", [0] = U"x", [1] = { 1, 2, 3 }, [1] = U"y" }; mix("t_char32_2d_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_excess_auto(void) { char32_t v[2][3] = { U"ab", U"c", U"d" }; mix("t_char32_2d_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_excess_static(void) { static char32_t v[2][3] = { U"ab", U"c", U"d" }; mix("t_char32_2d_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_braced_override_auto(void) { char32_t v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_char32_2d_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_2d_braced_override_static(void) { static char32_t v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_char32_2d_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_3d_mid_desig_auto(void) { char32_t v[2][2][4] = { [1] = { [1] = U"hi" }, [0][1] = U"j", U"k" }; mix("t_char32_3d_mid_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_3d_mid_desig_static(void) { static char32_t v[2][2][4] = { [1] = { [1] = U"hi" }, [0][1] = U"j", U"k" }; mix("t_char32_3d_mid_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_desig_chain_auto(void) { struct { int g; char32_t a[3][4]; int k; } v = { .a[1] = U"xy", U"z", .k = 3 }; mix("t_char32_member_desig_chain_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_desig_chain_static(void) { static struct { int g; char32_t a[3][4]; int k; } v = { .a[1] = U"xy", U"z", .k = 3 }; mix("t_char32_member_desig_chain_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_desig_elem_auto(void) { struct { int g; char32_t a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_char32_member_desig_elem_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_desig_elem_static(void) { static struct { int g; char32_t a[2][4]; int k; } v = { .a[1][2] = 65, 66, 67, .g = 4 }; mix("t_char32_member_desig_elem_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_2d_desig_rows_auto(void) { struct { char32_t a[3][3]; int k; } v = { { [2] = U"p", [0] = { 1 } }, 8 }; mix("t_char32_member_2d_desig_rows_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_member_2d_desig_rows_static(void) { static struct { char32_t a[3][3]; int k; } v = { { [2] = U"p", [0] = { 1 } }, 8 }; mix("t_char32_member_2d_desig_rows_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_union_2d_auto(void) { union { char32_t s[2][3]; long long x[2]; } v = { U"a", U"bc" }; mix("t_char32_union_2d_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_union_2d_static(void) { static union { char32_t s[2][3]; long long x[2]; } v = { U"a", U"bc" }; mix("t_char32_union_2d_static", &v, sizeof v); }
__attribute__((noinline)) static void t_char32_cl_unsized(void) { const char32_t *p = (char32_t[]){ U"a\U0001F600" }; mix("t_char32_cl_unsized", p, sizeof((char32_t[]){ U"a\U0001F600" })); }
__attribute__((noinline)) static void t_char32_cl_sized(void) { const char32_t *p = (char32_t[5]){ U"ab" }; mix("t_char32_cl_sized", p, 5 * sizeof(char32_t)); }
__attribute__((noinline)) static void t_char32_cl_2d(void) { const char32_t (*p)[3] = (char32_t[2][3]){ U"ab", U"c" }; mix("t_char32_cl_2d", p, 6 * sizeof(char32_t)); }
__attribute__((noinline)) static void t_char32_cl_struct(void) { struct cs_char32 { char32_t a[4]; int g; }; const struct cs_char32 *p = &(struct cs_char32){ U"ab", 4 }; mix("t_char32_cl_struct", p, sizeof *p); }
static char32_t g_char32_2d[2][4] = { U"ab", U"c\U0001F600" };
__attribute__((noinline)) static void t_g_char32_2d(void) { mix("t_g_char32_2d", &g_char32_2d, sizeof g_char32_2d); }
static struct { char32_t a[3]; char32_t w[3]; } g_char32_member = { U"ab", U"cd" };
__attribute__((noinline)) static void t_g_char32_member(void) { mix("t_g_char32_member", &g_char32_member, sizeof g_char32_member); }
static struct { char32_t a[3]; int k; } g_char32_arr_struct[2] = { { U"ab", 1 }, { U"e", 2 } };
__attribute__((noinline)) static void t_g_char32_arr_struct(void) { mix("t_g_char32_arr_struct", &g_char32_arr_struct, sizeof g_char32_arr_struct); }
static struct { int n; char32_t s[]; } g_char32_fam = { 3, U"ab" };
__attribute__((noinline)) static void t_g_char32_fam(void) { mix("t_g_char32_fam", &g_char32_fam, sizeof g_char32_fam + 3 * sizeof(char32_t)); }
static struct { const char32_t *p; char32_t a[3]; } g_char32_ptrmix = { 0, U"ab" };
__attribute__((noinline)) static void t_g_char32_ptrmix(void) { mix("t_g_char32_ptrmix", &g_char32_ptrmix, sizeof g_char32_ptrmix); }
static struct { const char32_t *p; char32_t a[2][3]; int k; } g_char32_ptrmix_2d = { g_char32_2d[1], U"ab", U"c", 4 };
__attribute__((noinline)) static void t_g_char32_ptrmix_2d(void) { mix("t_g_char32_ptrmix_2d", g_char32_ptrmix_2d.a, sizeof g_char32_ptrmix_2d - (size_t)((char *)g_char32_ptrmix_2d.a - (char *)&g_char32_ptrmix_2d)); if (g_char32_ptrmix_2d.p != g_char32_2d[1]) puts("t_g_char32_ptrmix_2d BADPTR"); }
static struct { const char32_t *p; char32_t a[2][3]; int k; } g_char32_ptrmix_2d_desig = { .a[1] = U"d", .p = 0, .k = 2 };
__attribute__((noinline)) static void t_g_char32_ptrmix_2d_desig(void) { mix("t_g_char32_ptrmix_2d_desig", &g_char32_ptrmix_2d_desig, sizeof g_char32_ptrmix_2d_desig); }
static struct { int n; char32_t s[]; } g_char32_fam_big = { 3, U"a\U0001F600" };
__attribute__((noinline)) static void t_g_char32_fam_big(void) { mix("t_g_char32_fam_big", &g_char32_fam_big, sizeof g_char32_fam_big + 3 * sizeof(char32_t)); }
static struct { const void *p; struct { char32_t s[4]; char32_t m[2][3]; int k; } in; } g_char32_nested_ptr = { 0, { U"ab", U"c", U"d", 5 } };
__attribute__((noinline)) static void t_g_char32_nested_ptr(void) { mix("t_g_char32_nested_ptr", &g_char32_nested_ptr, sizeof g_char32_nested_ptr); }
static struct { const void *p; char32_t s[3]; char32_t m[2][2]; } g_char32_arr_ptr_flat[2] = { { 0, U"a", U"b" }, 0, U"bc", U"d", U"e" };
__attribute__((noinline)) static void t_g_char32_arr_ptr_flat(void) { mix("t_g_char32_arr_ptr_flat", &g_char32_arr_ptr_flat, sizeof g_char32_arr_ptr_flat); }
static struct { const void *p; struct { int k; char32_t m[3][3]; } in; } g_char32_nested_ptr_desig = { .in.m[1] = U"x", U"yz", .p = 0, .in.k = 7 };
__attribute__((noinline)) static void t_g_char32_nested_ptr_desig(void) { mix("t_g_char32_nested_ptr_desig", &g_char32_nested_ptr_desig, sizeof g_char32_nested_ptr_desig); }
static char32_t g_char32_3d_desig[2][2][3] = { [1][1] = U"z", [0] = { U"a", U"b" } };
__attribute__((noinline)) static void t_g_char32_3d_desig(void) { mix("t_g_char32_3d_desig", &g_char32_3d_desig, sizeof g_char32_3d_desig); }
__attribute__((noinline)) static void t_int_md_flat_auto(void) { struct { int a[2][2]; int g; } v = { 1, 2, 3, 4, 5 }; mix("t_int_md_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_flat_static(void) { static struct { int a[2][2]; int g; } v = { 1, 2, 3, 4, 5 }; mix("t_int_md_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_partial_row_auto(void) { struct { int a[2][2]; int g; } v = { { 1, 2, 3 }, 5 }; mix("t_int_md_partial_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_partial_row_static(void) { static struct { int a[2][2]; int g; } v = { { 1, 2, 3 }, 5 }; mix("t_int_md_partial_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_short_row_auto(void) { struct { int a[2][3]; int g; } v = { { 1, 2 }, 7 }; mix("t_int_md_short_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_short_row_static(void) { static struct { int a[2][3]; int g; } v = { { 1, 2 }, 7 }; mix("t_int_md_short_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_desig_auto(void) { struct { int a[2][2]; int g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_int_md_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_desig_static(void) { static struct { int a[2][2]; int g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_int_md_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_inner_desig_auto(void) { struct { int a[2][2]; int g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_int_md_inner_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_inner_desig_static(void) { static struct { int a[2][2]; int g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_int_md_inner_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_nested_auto(void) { struct { int k; struct { int a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_int_md_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_nested_static(void) { static struct { int k; struct { int a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_int_md_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_nested_flat_auto(void) { struct { int k; struct { int a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_int_md_nested_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_nested_flat_static(void) { static struct { int k; struct { int a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_int_md_nested_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_3d_desig_auto(void) { int v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_int_3d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_3d_desig_static(void) { static int v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_int_3d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_then_scalar_members_auto(void) { struct { int a[2][2]; int b[2]; int g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_int_md_then_scalar_members_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_then_scalar_members_static(void) { static struct { int a[2][2]; int b[2]; int g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_int_md_then_scalar_members_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_excess_auto(void) { struct { int a[2][2]; int g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_int_md_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_excess_static(void) { static struct { int a[2][2]; int g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_int_md_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_desig_continue_auto(void) { struct { int a[2][3]; int g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_int_md_desig_continue_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_desig_continue_static(void) { static struct { int a[2][3]; int g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_int_md_desig_continue_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_braced_override_auto(void) { int v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_int_md_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_braced_override_static(void) { static int v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_int_md_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_nested_level_desig_auto(void) { int v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_int_md_nested_level_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_nested_level_desig_static(void) { static int v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_int_md_nested_level_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_values_auto(void) { int v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_int_md_values_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_values_static(void) { static int v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_int_md_values_static", &v, sizeof v); }
__attribute__((noinline)) static void t_int_md_cl(void) { const int (*p)[3] = (int[2][3]){ [1][1] = 7, 8, [0] = { 1 }, 2 }; mix("t_int_md_cl", p, sizeof(int[2][3])); }
__attribute__((noinline)) static void t_short_md_flat_auto(void) { struct { short a[2][2]; short g; } v = { 1, 2, 3, 4, 5 }; mix("t_short_md_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_flat_static(void) { static struct { short a[2][2]; short g; } v = { 1, 2, 3, 4, 5 }; mix("t_short_md_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_partial_row_auto(void) { struct { short a[2][2]; short g; } v = { { 1, 2, 3 }, 5 }; mix("t_short_md_partial_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_partial_row_static(void) { static struct { short a[2][2]; short g; } v = { { 1, 2, 3 }, 5 }; mix("t_short_md_partial_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_short_row_auto(void) { struct { short a[2][3]; short g; } v = { { 1, 2 }, 7 }; mix("t_short_md_short_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_short_row_static(void) { static struct { short a[2][3]; short g; } v = { { 1, 2 }, 7 }; mix("t_short_md_short_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_desig_auto(void) { struct { short a[2][2]; short g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_short_md_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_desig_static(void) { static struct { short a[2][2]; short g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_short_md_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_inner_desig_auto(void) { struct { short a[2][2]; short g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_short_md_inner_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_inner_desig_static(void) { static struct { short a[2][2]; short g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_short_md_inner_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_nested_auto(void) { struct { short k; struct { short a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_short_md_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_nested_static(void) { static struct { short k; struct { short a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_short_md_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_nested_flat_auto(void) { struct { short k; struct { short a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_short_md_nested_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_nested_flat_static(void) { static struct { short k; struct { short a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_short_md_nested_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_3d_desig_auto(void) { short v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_short_3d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_3d_desig_static(void) { static short v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_short_3d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_then_scalar_members_auto(void) { struct { short a[2][2]; short b[2]; short g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_short_md_then_scalar_members_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_then_scalar_members_static(void) { static struct { short a[2][2]; short b[2]; short g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_short_md_then_scalar_members_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_excess_auto(void) { struct { short a[2][2]; short g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_short_md_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_excess_static(void) { static struct { short a[2][2]; short g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_short_md_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_desig_continue_auto(void) { struct { short a[2][3]; short g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_short_md_desig_continue_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_desig_continue_static(void) { static struct { short a[2][3]; short g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_short_md_desig_continue_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_braced_override_auto(void) { short v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_short_md_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_braced_override_static(void) { static short v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_short_md_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_nested_level_desig_auto(void) { short v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_short_md_nested_level_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_nested_level_desig_static(void) { static short v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_short_md_nested_level_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_values_auto(void) { short v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_short_md_values_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_values_static(void) { static short v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_short_md_values_static", &v, sizeof v); }
__attribute__((noinline)) static void t_short_md_cl(void) { const short (*p)[3] = (short[2][3]){ [1][1] = 7, 8, [0] = { 1 }, 2 }; mix("t_short_md_cl", p, sizeof(short[2][3])); }
__attribute__((noinline)) static void t_double_md_flat_auto(void) { struct { double a[2][2]; double g; } v = { 1, 2, 3, 4, 5 }; mix("t_double_md_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_flat_static(void) { static struct { double a[2][2]; double g; } v = { 1, 2, 3, 4, 5 }; mix("t_double_md_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_partial_row_auto(void) { struct { double a[2][2]; double g; } v = { { 1, 2, 3 }, 5 }; mix("t_double_md_partial_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_partial_row_static(void) { static struct { double a[2][2]; double g; } v = { { 1, 2, 3 }, 5 }; mix("t_double_md_partial_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_short_row_auto(void) { struct { double a[2][3]; double g; } v = { { 1, 2 }, 7 }; mix("t_double_md_short_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_short_row_static(void) { static struct { double a[2][3]; double g; } v = { { 1, 2 }, 7 }; mix("t_double_md_short_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_desig_auto(void) { struct { double a[2][2]; double g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_double_md_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_desig_static(void) { static struct { double a[2][2]; double g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_double_md_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_inner_desig_auto(void) { struct { double a[2][2]; double g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_double_md_inner_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_inner_desig_static(void) { static struct { double a[2][2]; double g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_double_md_inner_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_nested_auto(void) { struct { double k; struct { double a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_double_md_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_nested_static(void) { static struct { double k; struct { double a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_double_md_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_nested_flat_auto(void) { struct { double k; struct { double a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_double_md_nested_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_nested_flat_static(void) { static struct { double k; struct { double a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_double_md_nested_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_3d_desig_auto(void) { double v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_double_3d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_3d_desig_static(void) { static double v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_double_3d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_then_scalar_members_auto(void) { struct { double a[2][2]; double b[2]; double g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_double_md_then_scalar_members_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_then_scalar_members_static(void) { static struct { double a[2][2]; double b[2]; double g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_double_md_then_scalar_members_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_excess_auto(void) { struct { double a[2][2]; double g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_double_md_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_excess_static(void) { static struct { double a[2][2]; double g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_double_md_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_desig_continue_auto(void) { struct { double a[2][3]; double g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_double_md_desig_continue_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_desig_continue_static(void) { static struct { double a[2][3]; double g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_double_md_desig_continue_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_braced_override_auto(void) { double v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_double_md_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_braced_override_static(void) { static double v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_double_md_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_nested_level_desig_auto(void) { double v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_double_md_nested_level_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_nested_level_desig_static(void) { static double v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_double_md_nested_level_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_values_auto(void) { double v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_double_md_values_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_values_static(void) { static double v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_double_md_values_static", &v, sizeof v); }
__attribute__((noinline)) static void t_double_md_cl(void) { const double (*p)[3] = (double[2][3]){ [1][1] = 7, 8, [0] = { 1 }, 2 }; mix("t_double_md_cl", p, sizeof(double[2][3])); }
__attribute__((noinline)) static void t_unsigned_char_md_flat_auto(void) { struct { unsigned char a[2][2]; unsigned char g; } v = { 1, 2, 3, 4, 5 }; mix("t_unsigned_char_md_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_flat_static(void) { static struct { unsigned char a[2][2]; unsigned char g; } v = { 1, 2, 3, 4, 5 }; mix("t_unsigned_char_md_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_partial_row_auto(void) { struct { unsigned char a[2][2]; unsigned char g; } v = { { 1, 2, 3 }, 5 }; mix("t_unsigned_char_md_partial_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_partial_row_static(void) { static struct { unsigned char a[2][2]; unsigned char g; } v = { { 1, 2, 3 }, 5 }; mix("t_unsigned_char_md_partial_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_short_row_auto(void) { struct { unsigned char a[2][3]; unsigned char g; } v = { { 1, 2 }, 7 }; mix("t_unsigned_char_md_short_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_short_row_static(void) { static struct { unsigned char a[2][3]; unsigned char g; } v = { { 1, 2 }, 7 }; mix("t_unsigned_char_md_short_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_desig_auto(void) { struct { unsigned char a[2][2]; unsigned char g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_unsigned_char_md_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_desig_static(void) { static struct { unsigned char a[2][2]; unsigned char g; } v = { .a[1][0] = 9, .g = 3 }; mix("t_unsigned_char_md_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_inner_desig_auto(void) { struct { unsigned char a[2][2]; unsigned char g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_unsigned_char_md_inner_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_inner_desig_static(void) { static struct { unsigned char a[2][2]; unsigned char g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t_unsigned_char_md_inner_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_nested_auto(void) { struct { unsigned char k; struct { unsigned char a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_unsigned_char_md_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_nested_static(void) { static struct { unsigned char k; struct { unsigned char a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t_unsigned_char_md_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_nested_flat_auto(void) { struct { unsigned char k; struct { unsigned char a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_unsigned_char_md_nested_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_nested_flat_static(void) { static struct { unsigned char k; struct { unsigned char a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_unsigned_char_md_nested_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_3d_desig_auto(void) { unsigned char v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_unsigned_char_3d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_3d_desig_static(void) { static unsigned char v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t_unsigned_char_3d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_then_scalar_members_auto(void) { struct { unsigned char a[2][2]; unsigned char b[2]; unsigned char g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_unsigned_char_md_then_scalar_members_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_then_scalar_members_static(void) { static struct { unsigned char a[2][2]; unsigned char b[2]; unsigned char g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t_unsigned_char_md_then_scalar_members_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_excess_auto(void) { struct { unsigned char a[2][2]; unsigned char g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_unsigned_char_md_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_excess_static(void) { static struct { unsigned char a[2][2]; unsigned char g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t_unsigned_char_md_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_desig_continue_auto(void) { struct { unsigned char a[2][3]; unsigned char g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_unsigned_char_md_desig_continue_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_desig_continue_static(void) { static struct { unsigned char a[2][3]; unsigned char g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t_unsigned_char_md_desig_continue_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_braced_override_auto(void) { unsigned char v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_unsigned_char_md_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_braced_override_static(void) { static unsigned char v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t_unsigned_char_md_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_nested_level_desig_auto(void) { unsigned char v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_unsigned_char_md_nested_level_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_nested_level_desig_static(void) { static unsigned char v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t_unsigned_char_md_nested_level_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_values_auto(void) { unsigned char v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_unsigned_char_md_values_auto", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_values_static(void) { static unsigned char v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t_unsigned_char_md_values_static", &v, sizeof v); }
__attribute__((noinline)) static void t_unsigned_char_md_cl(void) { const unsigned char (*p)[3] = (unsigned char[2][3]){ [1][1] = 7, 8, [0] = { 1 }, 2 }; mix("t_unsigned_char_md_cl", p, sizeof(unsigned char[2][3])); }
__attribute__((noinline)) static void t__Bool_md_flat_auto(void) { struct { _Bool a[2][2]; _Bool g; } v = { 1, 2, 3, 4, 5 }; mix("t__Bool_md_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_flat_static(void) { static struct { _Bool a[2][2]; _Bool g; } v = { 1, 2, 3, 4, 5 }; mix("t__Bool_md_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_partial_row_auto(void) { struct { _Bool a[2][2]; _Bool g; } v = { { 1, 2, 3 }, 5 }; mix("t__Bool_md_partial_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_partial_row_static(void) { static struct { _Bool a[2][2]; _Bool g; } v = { { 1, 2, 3 }, 5 }; mix("t__Bool_md_partial_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_short_row_auto(void) { struct { _Bool a[2][3]; _Bool g; } v = { { 1, 2 }, 7 }; mix("t__Bool_md_short_row_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_short_row_static(void) { static struct { _Bool a[2][3]; _Bool g; } v = { { 1, 2 }, 7 }; mix("t__Bool_md_short_row_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_desig_auto(void) { struct { _Bool a[2][2]; _Bool g; } v = { .a[1][0] = 9, .g = 3 }; mix("t__Bool_md_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_desig_static(void) { static struct { _Bool a[2][2]; _Bool g; } v = { .a[1][0] = 9, .g = 3 }; mix("t__Bool_md_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_inner_desig_auto(void) { struct { _Bool a[2][2]; _Bool g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t__Bool_md_inner_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_inner_desig_static(void) { static struct { _Bool a[2][2]; _Bool g; } v = { { [1] = { 4 }, [0][1] = 2 }, 1 }; mix("t__Bool_md_inner_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_nested_auto(void) { struct { _Bool k; struct { _Bool a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t__Bool_md_nested_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_nested_static(void) { static struct { _Bool k; struct { _Bool a[2][2]; } in[2]; } v = { 1, { { { { 1, 2 }, { 3 } } }, { 5, 6, 7 } } }; mix("t__Bool_md_nested_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_nested_flat_auto(void) { struct { _Bool k; struct { _Bool a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t__Bool_md_nested_flat_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_nested_flat_static(void) { static struct { _Bool k; struct { _Bool a[2][2]; } in[2]; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t__Bool_md_nested_flat_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_3d_desig_auto(void) { _Bool v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t__Bool_3d_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_3d_desig_static(void) { static _Bool v[2][2][2] = { [1][0] = { 1, 2 }, [0] = 3, 4 }; mix("t__Bool_3d_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_then_scalar_members_auto(void) { struct { _Bool a[2][2]; _Bool b[2]; _Bool g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t__Bool_md_then_scalar_members_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_then_scalar_members_static(void) { static struct { _Bool a[2][2]; _Bool b[2]; _Bool g; } v = { 1, 2, 3, 4, 5, 6, 7 }; mix("t__Bool_md_then_scalar_members_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_excess_auto(void) { struct { _Bool a[2][2]; _Bool g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t__Bool_md_excess_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_excess_static(void) { static struct { _Bool a[2][2]; _Bool g; } v = { { { 1, 2, 9 }, { 3 }, { 8 } }, 5 }; mix("t__Bool_md_excess_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_desig_continue_auto(void) { struct { _Bool a[2][3]; _Bool g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t__Bool_md_desig_continue_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_desig_continue_static(void) { static struct { _Bool a[2][3]; _Bool g; } v = { .a[0][2] = 1, 2, 3, .g = 4 }; mix("t__Bool_md_desig_continue_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_braced_override_auto(void) { _Bool v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t__Bool_md_braced_override_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_braced_override_static(void) { static _Bool v[2][3] = { [0][2] = 9, [0] = { 4 }, [1][1] = 5, [1] = 6 }; mix("t__Bool_md_braced_override_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_nested_level_desig_auto(void) { _Bool v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t__Bool_md_nested_level_desig_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_nested_level_desig_static(void) { static _Bool v[3][2][2] = { { 1 }, { [1] = { [1] = 4 }, [0][0] = 2 }, 3 }; mix("t__Bool_md_nested_level_desig_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_values_auto(void) { _Bool v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t__Bool_md_values_auto", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_values_static(void) { static _Bool v[2][3] = { { -1, 2, 0 }, { 256, 3, 0 } }; mix("t__Bool_md_values_static", &v, sizeof v); }
__attribute__((noinline)) static void t__Bool_md_cl(void) { const _Bool (*p)[3] = (_Bool[2][3]){ [1][1] = 7, 8, [0] = { 1 }, 2 }; mix("t__Bool_md_cl", p, sizeof(_Bool[2][3])); }
int main(void) {
  dirty(); t_char_1d_short_auto();
  dirty(); t_char_1d_short_static();
  dirty(); t_char_1d_exact_auto();
  dirty(); t_char_1d_exact_static();
  dirty(); t_char_1d_unsized_auto();
  dirty(); t_char_1d_unsized_static();
  dirty(); t_char_1d_braced_auto();
  dirty(); t_char_1d_braced_static();
  dirty(); t_char_2d_auto();
  dirty(); t_char_2d_static();
  dirty(); t_char_2d_braced_auto();
  dirty(); t_char_2d_braced_static();
  dirty(); t_char_2d_desig_auto();
  dirty(); t_char_2d_desig_static();
  dirty(); t_char_2d_unsized_auto();
  dirty(); t_char_2d_unsized_static();
  dirty(); t_char_3d_auto();
  dirty(); t_char_3d_static();
  dirty(); t_char_member_auto();
  dirty(); t_char_member_static();
  dirty(); t_char_member_braced_auto();
  dirty(); t_char_member_braced_static();
  dirty(); t_char_member_desig_auto();
  dirty(); t_char_member_desig_static();
  dirty(); t_char_member_2d_auto();
  dirty(); t_char_member_2d_static();
  dirty(); t_char_member_flat2d_auto();
  dirty(); t_char_member_flat2d_static();
  dirty(); t_char_nested_auto();
  dirty(); t_char_nested_static();
  dirty(); t_char_arr_of_struct_auto();
  dirty(); t_char_arr_of_struct_static();
  dirty(); t_char_arr_of_struct_flat_auto();
  dirty(); t_char_arr_of_struct_flat_static();
  dirty(); t_char_union_auto();
  dirty(); t_char_union_static();
  dirty(); t_char_2d_override_auto();
  dirty(); t_char_2d_override_static();
  dirty(); t_char_2d_excess_auto();
  dirty(); t_char_2d_excess_static();
  dirty(); t_char_2d_braced_override_auto();
  dirty(); t_char_2d_braced_override_static();
  dirty(); t_char_3d_mid_desig_auto();
  dirty(); t_char_3d_mid_desig_static();
  dirty(); t_char_member_desig_chain_auto();
  dirty(); t_char_member_desig_chain_static();
  dirty(); t_char_member_desig_elem_auto();
  dirty(); t_char_member_desig_elem_static();
  dirty(); t_char_member_2d_desig_rows_auto();
  dirty(); t_char_member_2d_desig_rows_static();
  dirty(); t_char_union_2d_auto();
  dirty(); t_char_union_2d_static();
  dirty(); t_char_cl_unsized();
  dirty(); t_char_cl_sized();
  dirty(); t_char_cl_2d();
  dirty(); t_char_cl_struct();
  dirty(); t_g_char_2d();
  dirty(); t_g_char_member();
  dirty(); t_g_char_arr_struct();
  dirty(); t_g_char_fam();
  dirty(); t_g_char_ptrmix();
  dirty(); t_g_char_ptrmix_2d();
  dirty(); t_g_char_ptrmix_2d_desig();
  dirty(); t_g_char_fam_big();
  dirty(); t_g_char_nested_ptr();
  dirty(); t_g_char_arr_ptr_flat();
  dirty(); t_g_char_nested_ptr_desig();
  dirty(); t_g_char_3d_desig();
  dirty(); t_char16_1d_short_auto();
  dirty(); t_char16_1d_short_static();
  dirty(); t_char16_1d_exact_auto();
  dirty(); t_char16_1d_exact_static();
  dirty(); t_char16_1d_unsized_auto();
  dirty(); t_char16_1d_unsized_static();
  dirty(); t_char16_1d_braced_auto();
  dirty(); t_char16_1d_braced_static();
  dirty(); t_char16_2d_auto();
  dirty(); t_char16_2d_static();
  dirty(); t_char16_2d_braced_auto();
  dirty(); t_char16_2d_braced_static();
  dirty(); t_char16_2d_desig_auto();
  dirty(); t_char16_2d_desig_static();
  dirty(); t_char16_2d_unsized_auto();
  dirty(); t_char16_2d_unsized_static();
  dirty(); t_char16_3d_auto();
  dirty(); t_char16_3d_static();
  dirty(); t_char16_member_auto();
  dirty(); t_char16_member_static();
  dirty(); t_char16_member_braced_auto();
  dirty(); t_char16_member_braced_static();
  dirty(); t_char16_member_desig_auto();
  dirty(); t_char16_member_desig_static();
  dirty(); t_char16_member_2d_auto();
  dirty(); t_char16_member_2d_static();
  dirty(); t_char16_member_flat2d_auto();
  dirty(); t_char16_member_flat2d_static();
  dirty(); t_char16_nested_auto();
  dirty(); t_char16_nested_static();
  dirty(); t_char16_arr_of_struct_auto();
  dirty(); t_char16_arr_of_struct_static();
  dirty(); t_char16_arr_of_struct_flat_auto();
  dirty(); t_char16_arr_of_struct_flat_static();
  dirty(); t_char16_union_auto();
  dirty(); t_char16_union_static();
  dirty(); t_char16_2d_override_auto();
  dirty(); t_char16_2d_override_static();
  dirty(); t_char16_2d_excess_auto();
  dirty(); t_char16_2d_excess_static();
  dirty(); t_char16_2d_braced_override_auto();
  dirty(); t_char16_2d_braced_override_static();
  dirty(); t_char16_3d_mid_desig_auto();
  dirty(); t_char16_3d_mid_desig_static();
  dirty(); t_char16_member_desig_chain_auto();
  dirty(); t_char16_member_desig_chain_static();
  dirty(); t_char16_member_desig_elem_auto();
  dirty(); t_char16_member_desig_elem_static();
  dirty(); t_char16_member_2d_desig_rows_auto();
  dirty(); t_char16_member_2d_desig_rows_static();
  dirty(); t_char16_union_2d_auto();
  dirty(); t_char16_union_2d_static();
  dirty(); t_char16_cl_unsized();
  dirty(); t_char16_cl_sized();
  dirty(); t_char16_cl_2d();
  dirty(); t_char16_cl_struct();
  dirty(); t_g_char16_2d();
  dirty(); t_g_char16_member();
  dirty(); t_g_char16_arr_struct();
  dirty(); t_g_char16_fam();
  dirty(); t_g_char16_ptrmix();
  dirty(); t_g_char16_ptrmix_2d();
  dirty(); t_g_char16_ptrmix_2d_desig();
  dirty(); t_g_char16_fam_big();
  dirty(); t_g_char16_nested_ptr();
  dirty(); t_g_char16_arr_ptr_flat();
  dirty(); t_g_char16_nested_ptr_desig();
  dirty(); t_g_char16_3d_desig();
  dirty(); t_wchar_1d_short_auto();
  dirty(); t_wchar_1d_short_static();
  dirty(); t_wchar_1d_exact_auto();
  dirty(); t_wchar_1d_exact_static();
  dirty(); t_wchar_1d_unsized_auto();
  dirty(); t_wchar_1d_unsized_static();
  dirty(); t_wchar_1d_braced_auto();
  dirty(); t_wchar_1d_braced_static();
  dirty(); t_wchar_2d_auto();
  dirty(); t_wchar_2d_static();
  dirty(); t_wchar_2d_braced_auto();
  dirty(); t_wchar_2d_braced_static();
  dirty(); t_wchar_2d_desig_auto();
  dirty(); t_wchar_2d_desig_static();
  dirty(); t_wchar_2d_unsized_auto();
  dirty(); t_wchar_2d_unsized_static();
  dirty(); t_wchar_3d_auto();
  dirty(); t_wchar_3d_static();
  dirty(); t_wchar_member_auto();
  dirty(); t_wchar_member_static();
  dirty(); t_wchar_member_braced_auto();
  dirty(); t_wchar_member_braced_static();
  dirty(); t_wchar_member_desig_auto();
  dirty(); t_wchar_member_desig_static();
  dirty(); t_wchar_member_2d_auto();
  dirty(); t_wchar_member_2d_static();
  dirty(); t_wchar_member_flat2d_auto();
  dirty(); t_wchar_member_flat2d_static();
  dirty(); t_wchar_nested_auto();
  dirty(); t_wchar_nested_static();
  dirty(); t_wchar_arr_of_struct_auto();
  dirty(); t_wchar_arr_of_struct_static();
  dirty(); t_wchar_arr_of_struct_flat_auto();
  dirty(); t_wchar_arr_of_struct_flat_static();
  dirty(); t_wchar_union_auto();
  dirty(); t_wchar_union_static();
  dirty(); t_wchar_2d_override_auto();
  dirty(); t_wchar_2d_override_static();
  dirty(); t_wchar_2d_excess_auto();
  dirty(); t_wchar_2d_excess_static();
  dirty(); t_wchar_2d_braced_override_auto();
  dirty(); t_wchar_2d_braced_override_static();
  dirty(); t_wchar_3d_mid_desig_auto();
  dirty(); t_wchar_3d_mid_desig_static();
  dirty(); t_wchar_member_desig_chain_auto();
  dirty(); t_wchar_member_desig_chain_static();
  dirty(); t_wchar_member_desig_elem_auto();
  dirty(); t_wchar_member_desig_elem_static();
  dirty(); t_wchar_member_2d_desig_rows_auto();
  dirty(); t_wchar_member_2d_desig_rows_static();
  dirty(); t_wchar_union_2d_auto();
  dirty(); t_wchar_union_2d_static();
  dirty(); t_wchar_cl_unsized();
  dirty(); t_wchar_cl_sized();
  dirty(); t_wchar_cl_2d();
  dirty(); t_wchar_cl_struct();
  dirty(); t_g_wchar_2d();
  dirty(); t_g_wchar_member();
  dirty(); t_g_wchar_arr_struct();
  dirty(); t_g_wchar_fam();
  dirty(); t_g_wchar_ptrmix();
  dirty(); t_g_wchar_ptrmix_2d();
  dirty(); t_g_wchar_ptrmix_2d_desig();
  dirty(); t_g_wchar_fam_big();
  dirty(); t_g_wchar_nested_ptr();
  dirty(); t_g_wchar_arr_ptr_flat();
  dirty(); t_g_wchar_nested_ptr_desig();
  dirty(); t_g_wchar_3d_desig();
  dirty(); t_char32_1d_short_auto();
  dirty(); t_char32_1d_short_static();
  dirty(); t_char32_1d_exact_auto();
  dirty(); t_char32_1d_exact_static();
  dirty(); t_char32_1d_unsized_auto();
  dirty(); t_char32_1d_unsized_static();
  dirty(); t_char32_1d_braced_auto();
  dirty(); t_char32_1d_braced_static();
  dirty(); t_char32_2d_auto();
  dirty(); t_char32_2d_static();
  dirty(); t_char32_2d_braced_auto();
  dirty(); t_char32_2d_braced_static();
  dirty(); t_char32_2d_desig_auto();
  dirty(); t_char32_2d_desig_static();
  dirty(); t_char32_2d_unsized_auto();
  dirty(); t_char32_2d_unsized_static();
  dirty(); t_char32_3d_auto();
  dirty(); t_char32_3d_static();
  dirty(); t_char32_member_auto();
  dirty(); t_char32_member_static();
  dirty(); t_char32_member_braced_auto();
  dirty(); t_char32_member_braced_static();
  dirty(); t_char32_member_desig_auto();
  dirty(); t_char32_member_desig_static();
  dirty(); t_char32_member_2d_auto();
  dirty(); t_char32_member_2d_static();
  dirty(); t_char32_member_flat2d_auto();
  dirty(); t_char32_member_flat2d_static();
  dirty(); t_char32_nested_auto();
  dirty(); t_char32_nested_static();
  dirty(); t_char32_arr_of_struct_auto();
  dirty(); t_char32_arr_of_struct_static();
  dirty(); t_char32_arr_of_struct_flat_auto();
  dirty(); t_char32_arr_of_struct_flat_static();
  dirty(); t_char32_union_auto();
  dirty(); t_char32_union_static();
  dirty(); t_char32_2d_override_auto();
  dirty(); t_char32_2d_override_static();
  dirty(); t_char32_2d_excess_auto();
  dirty(); t_char32_2d_excess_static();
  dirty(); t_char32_2d_braced_override_auto();
  dirty(); t_char32_2d_braced_override_static();
  dirty(); t_char32_3d_mid_desig_auto();
  dirty(); t_char32_3d_mid_desig_static();
  dirty(); t_char32_member_desig_chain_auto();
  dirty(); t_char32_member_desig_chain_static();
  dirty(); t_char32_member_desig_elem_auto();
  dirty(); t_char32_member_desig_elem_static();
  dirty(); t_char32_member_2d_desig_rows_auto();
  dirty(); t_char32_member_2d_desig_rows_static();
  dirty(); t_char32_union_2d_auto();
  dirty(); t_char32_union_2d_static();
  dirty(); t_char32_cl_unsized();
  dirty(); t_char32_cl_sized();
  dirty(); t_char32_cl_2d();
  dirty(); t_char32_cl_struct();
  dirty(); t_g_char32_2d();
  dirty(); t_g_char32_member();
  dirty(); t_g_char32_arr_struct();
  dirty(); t_g_char32_fam();
  dirty(); t_g_char32_ptrmix();
  dirty(); t_g_char32_ptrmix_2d();
  dirty(); t_g_char32_ptrmix_2d_desig();
  dirty(); t_g_char32_fam_big();
  dirty(); t_g_char32_nested_ptr();
  dirty(); t_g_char32_arr_ptr_flat();
  dirty(); t_g_char32_nested_ptr_desig();
  dirty(); t_g_char32_3d_desig();
  dirty(); t_int_md_flat_auto();
  dirty(); t_int_md_flat_static();
  dirty(); t_int_md_partial_row_auto();
  dirty(); t_int_md_partial_row_static();
  dirty(); t_int_md_short_row_auto();
  dirty(); t_int_md_short_row_static();
  dirty(); t_int_md_desig_auto();
  dirty(); t_int_md_desig_static();
  dirty(); t_int_md_inner_desig_auto();
  dirty(); t_int_md_inner_desig_static();
  dirty(); t_int_md_nested_auto();
  dirty(); t_int_md_nested_static();
  dirty(); t_int_md_nested_flat_auto();
  dirty(); t_int_md_nested_flat_static();
  dirty(); t_int_3d_desig_auto();
  dirty(); t_int_3d_desig_static();
  dirty(); t_int_md_then_scalar_members_auto();
  dirty(); t_int_md_then_scalar_members_static();
  dirty(); t_int_md_excess_auto();
  dirty(); t_int_md_excess_static();
  dirty(); t_int_md_desig_continue_auto();
  dirty(); t_int_md_desig_continue_static();
  dirty(); t_int_md_braced_override_auto();
  dirty(); t_int_md_braced_override_static();
  dirty(); t_int_md_nested_level_desig_auto();
  dirty(); t_int_md_nested_level_desig_static();
  dirty(); t_int_md_values_auto();
  dirty(); t_int_md_values_static();
  dirty(); t_int_md_cl();
  dirty(); t_short_md_flat_auto();
  dirty(); t_short_md_flat_static();
  dirty(); t_short_md_partial_row_auto();
  dirty(); t_short_md_partial_row_static();
  dirty(); t_short_md_short_row_auto();
  dirty(); t_short_md_short_row_static();
  dirty(); t_short_md_desig_auto();
  dirty(); t_short_md_desig_static();
  dirty(); t_short_md_inner_desig_auto();
  dirty(); t_short_md_inner_desig_static();
  dirty(); t_short_md_nested_auto();
  dirty(); t_short_md_nested_static();
  dirty(); t_short_md_nested_flat_auto();
  dirty(); t_short_md_nested_flat_static();
  dirty(); t_short_3d_desig_auto();
  dirty(); t_short_3d_desig_static();
  dirty(); t_short_md_then_scalar_members_auto();
  dirty(); t_short_md_then_scalar_members_static();
  dirty(); t_short_md_excess_auto();
  dirty(); t_short_md_excess_static();
  dirty(); t_short_md_desig_continue_auto();
  dirty(); t_short_md_desig_continue_static();
  dirty(); t_short_md_braced_override_auto();
  dirty(); t_short_md_braced_override_static();
  dirty(); t_short_md_nested_level_desig_auto();
  dirty(); t_short_md_nested_level_desig_static();
  dirty(); t_short_md_values_auto();
  dirty(); t_short_md_values_static();
  dirty(); t_short_md_cl();
  dirty(); t_double_md_flat_auto();
  dirty(); t_double_md_flat_static();
  dirty(); t_double_md_partial_row_auto();
  dirty(); t_double_md_partial_row_static();
  dirty(); t_double_md_short_row_auto();
  dirty(); t_double_md_short_row_static();
  dirty(); t_double_md_desig_auto();
  dirty(); t_double_md_desig_static();
  dirty(); t_double_md_inner_desig_auto();
  dirty(); t_double_md_inner_desig_static();
  dirty(); t_double_md_nested_auto();
  dirty(); t_double_md_nested_static();
  dirty(); t_double_md_nested_flat_auto();
  dirty(); t_double_md_nested_flat_static();
  dirty(); t_double_3d_desig_auto();
  dirty(); t_double_3d_desig_static();
  dirty(); t_double_md_then_scalar_members_auto();
  dirty(); t_double_md_then_scalar_members_static();
  dirty(); t_double_md_excess_auto();
  dirty(); t_double_md_excess_static();
  dirty(); t_double_md_desig_continue_auto();
  dirty(); t_double_md_desig_continue_static();
  dirty(); t_double_md_braced_override_auto();
  dirty(); t_double_md_braced_override_static();
  dirty(); t_double_md_nested_level_desig_auto();
  dirty(); t_double_md_nested_level_desig_static();
  dirty(); t_double_md_values_auto();
  dirty(); t_double_md_values_static();
  dirty(); t_double_md_cl();
  dirty(); t_unsigned_char_md_flat_auto();
  dirty(); t_unsigned_char_md_flat_static();
  dirty(); t_unsigned_char_md_partial_row_auto();
  dirty(); t_unsigned_char_md_partial_row_static();
  dirty(); t_unsigned_char_md_short_row_auto();
  dirty(); t_unsigned_char_md_short_row_static();
  dirty(); t_unsigned_char_md_desig_auto();
  dirty(); t_unsigned_char_md_desig_static();
  dirty(); t_unsigned_char_md_inner_desig_auto();
  dirty(); t_unsigned_char_md_inner_desig_static();
  dirty(); t_unsigned_char_md_nested_auto();
  dirty(); t_unsigned_char_md_nested_static();
  dirty(); t_unsigned_char_md_nested_flat_auto();
  dirty(); t_unsigned_char_md_nested_flat_static();
  dirty(); t_unsigned_char_3d_desig_auto();
  dirty(); t_unsigned_char_3d_desig_static();
  dirty(); t_unsigned_char_md_then_scalar_members_auto();
  dirty(); t_unsigned_char_md_then_scalar_members_static();
  dirty(); t_unsigned_char_md_excess_auto();
  dirty(); t_unsigned_char_md_excess_static();
  dirty(); t_unsigned_char_md_desig_continue_auto();
  dirty(); t_unsigned_char_md_desig_continue_static();
  dirty(); t_unsigned_char_md_braced_override_auto();
  dirty(); t_unsigned_char_md_braced_override_static();
  dirty(); t_unsigned_char_md_nested_level_desig_auto();
  dirty(); t_unsigned_char_md_nested_level_desig_static();
  dirty(); t_unsigned_char_md_values_auto();
  dirty(); t_unsigned_char_md_values_static();
  dirty(); t_unsigned_char_md_cl();
  dirty(); t__Bool_md_flat_auto();
  dirty(); t__Bool_md_flat_static();
  dirty(); t__Bool_md_partial_row_auto();
  dirty(); t__Bool_md_partial_row_static();
  dirty(); t__Bool_md_short_row_auto();
  dirty(); t__Bool_md_short_row_static();
  dirty(); t__Bool_md_desig_auto();
  dirty(); t__Bool_md_desig_static();
  dirty(); t__Bool_md_inner_desig_auto();
  dirty(); t__Bool_md_inner_desig_static();
  dirty(); t__Bool_md_nested_auto();
  dirty(); t__Bool_md_nested_static();
  dirty(); t__Bool_md_nested_flat_auto();
  dirty(); t__Bool_md_nested_flat_static();
  dirty(); t__Bool_3d_desig_auto();
  dirty(); t__Bool_3d_desig_static();
  dirty(); t__Bool_md_then_scalar_members_auto();
  dirty(); t__Bool_md_then_scalar_members_static();
  dirty(); t__Bool_md_excess_auto();
  dirty(); t__Bool_md_excess_static();
  dirty(); t__Bool_md_desig_continue_auto();
  dirty(); t__Bool_md_desig_continue_static();
  dirty(); t__Bool_md_braced_override_auto();
  dirty(); t__Bool_md_braced_override_static();
  dirty(); t__Bool_md_nested_level_desig_auto();
  dirty(); t__Bool_md_nested_level_desig_static();
  dirty(); t__Bool_md_values_auto();
  dirty(); t__Bool_md_values_static();
  dirty(); t__Bool_md_cl();
  printf("ALL %lx\n", H); return 0; }
