/* Exhaustive coverage for division and modulo by a constant.
 *
 * div_by_const replaces hardware div/idiv (20-90 cycles) with Hacker's Delight
 * multiply-and-shift sequences. The magic number and shift are computed per
 * divisor and per signedness, and the fixup differs between the unsigned
 * add-and-shift form and the signed sign-correction form, so the space of
 * ways to be wrong by one is large and a handful of spot checks cannot cover
 * it. A truncation bug in a neighbouring predicate (const_power_of_two reading
 * an I128 constant through to_i64) was found in this area, which is what
 * motivated pinning the whole table down.
 *
 * The oracle deliberately uses no division. For every (dividend, divisor) the
 * test asserts the defining properties of C's truncated division:
 *
 *   dividend == quotient * divisor + remainder      (exact, wrapping-checked)
 *   unsigned: remainder <  divisor
 *   signed:   |remainder| < |divisor| and sign(remainder) == sign(dividend)
 *
 * so a wrong quotient or remainder is caught without asking the compiler to
 * perform the very operation under test. The runner additionally diffs the
 * whole binary's output against GCC.
 */
#include <limits.h>
#include <stdio.h>

static unsigned long long fails;

/* The checkers are deliberately side-effect-free: they record the first
 * offending case in globals and main() reports it once at the end. Calling
 * printf from inside the checker puts six computed values live across a
 * variadic call at every one of the ~20000 check sites, which is a much
 * harder register-allocation problem than the arithmetic under test and made
 * the test report failures that belonged to the call, not to div_by_const. */
static const char *fail_kind;
static unsigned long long fail_n, fail_d, fail_q, fail_r;

static void record(const char *kind, unsigned long long n, unsigned long long d,
		   unsigned long long q, unsigned long long r)
{
	if (fails == 0) {
		fail_kind = kind;
		fail_n = n;
		fail_d = d;
		fail_q = q;
		fail_r = r;
	}
	fails++;
}

/* Unsigned 64: q = n/d, r = n%d, checked by the defining identity. */
static void check_u64(unsigned long long n, unsigned long long d)
{
	unsigned long long q = n / d;
	unsigned long long r = n % d;

	/* r >= d, or q*d + r failing to reproduce n, means the quotient is off
	 * by one -- which is exactly how a wrong magic number or shift shows
	 * up. */
	if (r >= d || q * d + r != n)
		record("u64", n, d, q, r);
}

/* Signed 64: C99 truncates toward zero, so the remainder takes the dividend's
 * sign and is bounded by |d|. */
static void check_s64(long long n, long long d)
{
	long long q = n / d;
	long long r = n % d;
	long long ad = d < 0 ? -d : d;
	long long ar = r < 0 ? -r : r;

	if (ar >= ad || (r != 0 && ((r < 0) != (n < 0))) || q * d + r != n)
		record("s64", (unsigned long long)n, (unsigned long long)d,
		       (unsigned long long)q, (unsigned long long)r);
}

static void check_u32(unsigned n, unsigned d)
{
	unsigned q = n / d;
	unsigned r = n % d;

	if (r >= d || q * d + r != n)
		record("u32", n, d, q, r);
}

static void check_s32(int n, int d)
{
	int q = n / d;
	int r = n % d;
	int ad = d < 0 ? -d : d;
	int ar = r < 0 ? -r : r;

	if (ar >= ad || (r != 0 && ((r < 0) != (n < 0))) || q * d + r != n)
		record("s32", (unsigned long long)(long long)n,
		       (unsigned long long)(long long)d,
		       (unsigned long long)(long long)q,
		       (unsigned long long)(long long)r);
}

/* The divisor MUST be a literal in each function. Driving the sweep from an
 * array of divisors makes every division a variable division, so
 * div_by_const never fires and the test silently verifies the hardware div
 * instead of the strength reduction it claims to cover. One noinline function
 * per divisor, generated by macro, keeps the dividend sweep exhaustive while
 * the divisor stays a compile-time constant. */

/* Divisors hit every branch of the magic-number construction: 1 and 2
 * (degenerate), powers of two, one below and above a power of two, small odd
 * values needing the add-and-shift fixup, magics needing the full 64-bit
 * range, and the extremes. */
#define U64_LIST(X) \
	X(1) X(2) X(3) X(4) X(5) X(6) X(7) X(8) X(9) X(10) X(11) X(12) \
	X(1000) X(4095) X(4096) X(4097) X(65535) X(65536) X(65537) \
	X(4294967295) X(4294967296) X(4294967297) \
	X(9223372036854775807) X(18446744073709551557)

#define S64_LIST(X) \
	X(1) X(2) X(3) X(5) X(6) X(7) X(10) X(1000) X(4096) X(4097) \
	X(65536) X(65537) X(2147483647) X(4294967296) X(9223372036854775783)

#define U32_LIST(X) \
	X(1) X(2) X(3) X(7) X(10) X(1000) X(4095) X(4096) X(4097) \
	X(65535) X(65536) X(65537) X(2147483647) X(4294967295)

#define S32_LIST(X) \
	X(1) X(2) X(3) X(7) X(10) X(1000) X(4096) X(4097) X(65536) \
	X(2147483647)

/* Negative divisors exercise the sign-correction form; one is generated for
 * every divisor in the signed lists so each sweep has its mirror. */

#define GEN_U64(D)                                                            \
	__attribute__((noinline)) static void u64_d##D(unsigned long long n)   \
	{                                                                    \
		check_u64(n, D##ULL);                                        \
	}
#define GEN_S64(D)                                                            \
	__attribute__((noinline)) static void s64_d##D(long long n)            \
	{                                                                    \
		check_s64(n, D##LL);                                         \
	}
#define GEN_S64NEG(D)                                                         \
	__attribute__((noinline)) static void s64_n##D(long long n)            \
	{                                                                    \
		check_s64(n, -(D##LL));                                      \
	}
#define GEN_U32(D)                                                            \
	__attribute__((noinline)) static void u32_d##D(unsigned n)             \
	{                                                                    \
		check_u32(n, D##u);                                          \
	}
#define GEN_S32(D)                                                            \
	__attribute__((noinline)) static void s32_d##D(int n)                  \
	{                                                                    \
		check_s32(n, D);                                             \
	}
#define GEN_S32NEG(D)                                                         \
	__attribute__((noinline)) static void s32_n##D(int n)                  \
	{                                                                    \
		check_s32(n, -(D));                                          \
	}

U64_LIST(GEN_U64)
S64_LIST(GEN_S64)
S64_LIST(GEN_S64NEG)
U32_LIST(GEN_U32)
S32_LIST(GEN_S32)
S32_LIST(GEN_S32NEG)

/* Dividends: zero, the extremes, and -- the case that exposes an off-by-one in
 * the fixup -- values immediately around multiples of the divisor. The
 * multipliers are odd so the products land on many distinct residues. */
#define SWEEP_U64(D)                                                          \
	do {                                                                 \
		unsigned long long k;                                        \
		int i;                                                       \
		u64_d##D(0); u64_d##D(1); u64_d##D(2);                       \
		u64_d##D(D##ULL - 1); u64_d##D(D##ULL); u64_d##D(D##ULL + 1); \
		u64_d##D(~0ULL); u64_d##D(~0ULL - 1);                        \
		u64_d##D(0x8000000000000000ULL);                             \
		u64_d##D(0x7fffffffffffffffULL);                             \
		for (k = 1, i = 0; i < 40 && k != 0; k *= 3, i++) {          \
			u64_d##D(k);                                         \
			if (k >= (D##ULL)) {                                 \
				u64_d##D(k - 1); u64_d##D(k + 1);            \
				u64_d##D(k - (D##ULL)); u64_d##D(k + (D##ULL)); \
			}                                                    \
		}                                                            \
	} while (0);

#define SWEEP_S64(D)                                                          \
	do {                                                                 \
		long long k;                                                 \
		int i;                                                       \
		s64_d##D(0); s64_d##D(1); s64_d##D(-1);                      \
		s64_d##D(LLONG_MAX); s64_d##D(LLONG_MIN + 1);                \
		s64_d##D((D##LL) - 1); s64_d##D(D##LL); s64_d##D((D##LL) + 1); \
		s64_d##D(-(D##LL));                                          \
		s64_n##D(0); s64_n##D(1); s64_n##D(-1);                      \
		s64_n##D(LLONG_MAX); s64_n##D(LLONG_MIN + 1);                \
		s64_n##D((D##LL) - 1); s64_n##D(D##LL); s64_n##D(-(D##LL));  \
		for (k = 1, i = 0; i < 40 && k > 0; k *= 3, i++) {           \
			s64_d##D(k); s64_d##D(-k);                           \
			s64_n##D(k); s64_n##D(-k);                           \
			if (k >= (D##LL)) {                                  \
				s64_d##D(k - 1); s64_d##D(k + 1);            \
				s64_d##D(-k - 1); s64_d##D(-k + 1);          \
			}                                                    \
		}                                                            \
	} while (0);

#define SWEEP_U32(D)                                                          \
	do {                                                                 \
		unsigned long long k;                                        \
		int i;                                                       \
		u32_d##D(0u); u32_d##D(1u); u32_d##D((D##u) - 1);            \
		u32_d##D(D##u); u32_d##D((D##u) + 1);                        \
		u32_d##D(0xffffffffu); u32_d##D(0x80000000u);                \
		for (k = 1, i = 0; i < 25 && k <= 0xffffffffULL; k *= 3, i++) { \
			u32_d##D((unsigned)k);                               \
			if (k >= (D##ULL)) {                                 \
				u32_d##D((unsigned)(k - 1));                 \
				u32_d##D((unsigned)(k + 1));                 \
			}                                                    \
		}                                                            \
	} while (0);

#define SWEEP_S32(D)                                                          \
	do {                                                                 \
		int k, i;                                                    \
		s32_d##D(0); s32_d##D(1); s32_d##D(-1);                      \
		s32_d##D(2147483647); s32_d##D((D) - 1); s32_d##D(D);        \
		s32_d##D((D) + 1); s32_d##D(-(D));                           \
		s32_n##D(0); s32_n##D(1); s32_n##D(-1);                      \
		s32_n##D(2147483647); s32_n##D((D) - 1); s32_n##D(-(D));     \
		for (k = 1, i = 0; i < 22 && k > 0; k *= 3, i++) {           \
			s32_d##D(k); s32_d##D(-k);                           \
			s32_n##D(k); s32_n##D(-k);                           \
		}                                                            \
		/* INT_MIN / -1 overflows the quotient and traps on x86, so   \
		 * it is excluded only for the -1 divisor. */                 \
		if ((D) != 1) {                                              \
			s32_d##D(-2147483647 - 1);                           \
			s32_n##D(-2147483647 - 1);                           \
		}                                                            \
	} while (0);

int main(void)
{
	U64_LIST(SWEEP_U64);
	S64_LIST(SWEEP_S64);
	U32_LIST(SWEEP_U32);
	S32_LIST(SWEEP_S32);

	if (fails)
		printf("FAIL %s %llu / %llu: q=%llu r=%llu, q*d+r=%llu\n",
		       fail_kind, fail_n, fail_d, fail_q, fail_r,
		       fail_q * fail_d + fail_r);
	printf("%s (%llu failures)\n", fails ? "FAILED" : "ALL-OK", fails);
	return fails ? 1 : 0;
}
