/* Folded-address liveness, chained constant-offset GEP: the ROOT pointer must
 * stay live to every folded access.
 *
 * The backend composes `GEP(GEP(p,+a),+b)` into one `a+b(%p)` addressing mode,
 * so the register the Load/Store reads is the ROOT, not the intermediate GEP
 * dest (which is never materialised). The inlined `findElem` walks the key in
 * a register-hungry loop between the GEP that forms &pSchema->in.idxHash and
 * the reads through it, and the caller's `continue` arm is laid out after the
 * inlined body -- which is what puts a HOLE in pSchema's live range exactly
 * over the folded accesses.
 *
 * Before the session-30 fix liveness stopped at the immediate base and dropped
 * GEP dests that feed another GEP from the fold set, so pSchema "died" at its
 * GEP and the hash loop took its register. That is sqlite3.50's
 * sqlite3FindIndex -> sqlite3HashFind -> findElementWithHash -> strHash chain,
 * which SIGSEGV'd at -O1 (open :memory:, CREATE TABLE).
 *
 * Regression anchor: with the chain walk disabled
 * (CCC_GEP_CHAIN_LIVENESS_DEPTH=1) this case miscompiles at -O1. Generated by
 * scripts/gen_gep_chain_stress.py seed 12; keep the generator as the
 * exhaustive version of this test (scripts/run_gep_chain_stress.sh).
 */

#include <stdio.h>
#include <string.h>

typedef struct Bucket { unsigned count; char **chain; } Bucket;
typedef struct Hash   { unsigned htsize; unsigned count; char *first;
                        Bucket *ht; } Hash;

static unsigned long long g_sink;   /* consumes every computed value */
typedef struct Inner  { char ipad[16]; Hash idxHash; } Inner;
typedef struct Schema { char pad0[8]; const char *zName; char pad1[24]; Inner in; } Schema;
typedef struct Db     { char dpad[24]; Schema *pSchema; } Db;
typedef struct DbList { char lpad[32]; Db *aDb; int nDb; long x[5]; } DbList;

/* Inlined into findIndex: burns a register walking the key, THEN reads the
 * folded fields of *pH.  `pH` is a chain of constant-offset GEPs from the
 * caller's Schema pointer, so every one of these reads must keep that root
 * register alive. */
static char *findElem(const Hash *pH, const char *pKey){
    char *elem = (char*)0;
    unsigned count = 0;
    unsigned h = 0;
    unsigned acc2 = 7u;
    unsigned n = 0;
    const char *z = pKey;
    if( pH->htsize==0 ) return (char*)0;
    while( z[0] ){
        h += 0xdfu & (unsigned char)*z;
        h *= 2654435761u;
        n += 1u;
        z++;
    }
    h += n;
    if( pH->ht ){
        Bucket *b = &pH->ht[h % pH->htsize];
        count = b->count;
        elem = count ? b->chain[0] : (char*)0;
        if( count && elem ) g_sink += (unsigned long long)pH->htsize + (unsigned long long)(pH->count);
    }else{
        elem = pH->first;
        count = pH->count;
        if( count==0 ) elem = (char*)0;
    }
    return elem;
}


static int dbIsNamed(DbList *db, int j, const char *zDb){
    return strcmp(db->aDb[j].pSchema->zName, zDb)==0;
}

/* sqlite3FindIndex(): the Schema pointer is the ROOT of the GEP chain and is
 * live across the inlined findElem() body. */
char *findIndex(DbList *db, const char *zName, const char *zDb){
    char *p = (char*)0;
    int i;
    long v0 = db->x[0];
    long v1 = db->x[1];
    long v2 = db->x[2];
    long v3 = db->x[3];
    long v4 = db->x[4];

    (void)dbIsNamed;
    for(i=0; i<db->nDb; i++){
        int j = (i<2) ? i^1 : i;                 /* search TEMP before MAIN */
        Schema *pSchema = db->aDb[j].pSchema;
        p = findElem(&pSchema->in.idxHash, zName);
        if( p ) break;
    }
    g_sink += (unsigned long long)(0+v0+v1+v2+v3+v4);
    return p;
}

static unsigned strHash(const char *z){
    unsigned h = 0;
    while( z[0] ){ h += 0xdfu & (unsigned char)*(z++); h *= 2654435761u; }
    return h;
}

int main(void){
    static char *val[3];
    static Schema s[3];
    static Db dbs[3];
    static Bucket tab0[8], tab1[8], tab2[8];
    static DbList dbl;
    char *r;
    int i;

    val[0] = "ZERO"; val[1] = "ONE"; val[2] = "TWO";
    for(i=0;i<8;i++){
        tab0[i].count = 0; tab0[i].chain = (char**)0;
        tab1[i].count = 0; tab1[i].chain = (char**)0;
        tab2[i].count = 0; tab2[i].chain = (char**)0;
    }
    s[0].zName = "temp";
    s[0].in.idxHash.htsize = 8;
    s[0].in.idxHash.count = 1;
    s[0].in.idxHash.first = val[0];
    s[0].in.idxHash.ht = tab0;
    s[1].zName = "main";
    s[1].in.idxHash.htsize = 8;
    s[1].in.idxHash.count = 1;
    s[1].in.idxHash.first = val[1];
    s[1].in.idxHash.ht = tab1;
    s[2].zName = "aux";
    s[2].in.idxHash.htsize = 8;
    s[2].in.idxHash.count = 1;
    s[2].in.idxHash.first = val[2];
    s[2].in.idxHash.ht = tab2;
    dbs[0].pSchema = &s[0]; dbs[1].pSchema = &s[1]; dbs[2].pSchema = &s[2];
    {
        unsigned hh = strHash("alpha") % 8;
        tab0[hh].count = 1;
        tab0[hh].chain = &val[0];
    }
    {
        unsigned hh = strHash("beta") % 8;
        tab1[hh].count = 1;
        tab1[hh].chain = &val[1];
    }
    {
        unsigned hh = strHash("gamma") % 8;
        tab2[hh].count = 1;
        tab2[hh].chain = &val[2];
    }
    dbl.aDb = dbs;
    dbl.nDb = 3;
    for(i=0;i<5;i++) dbl.x[i] = (long)i + 1;

    r = findIndex(&dbl, "alpha", 0);
    printf("%s|%s=%s\n", "alpha", 0, r ? r : "-");
    r = findIndex(&dbl, "alpha", "main");
    printf("%s|%s=%s\n", "alpha", "main", r ? r : "-");
    r = findIndex(&dbl, "alpha", "temp");
    printf("%s|%s=%s\n", "alpha", "temp", r ? r : "-");
    r = findIndex(&dbl, "beta", 0);
    printf("%s|%s=%s\n", "beta", 0, r ? r : "-");
    r = findIndex(&dbl, "beta", "main");
    printf("%s|%s=%s\n", "beta", "main", r ? r : "-");
    r = findIndex(&dbl, "beta", "temp");
    printf("%s|%s=%s\n", "beta", "temp", r ? r : "-");
    r = findIndex(&dbl, "gamma", 0);
    printf("%s|%s=%s\n", "gamma", 0, r ? r : "-");
    r = findIndex(&dbl, "gamma", "main");
    printf("%s|%s=%s\n", "gamma", "main", r ? r : "-");
    r = findIndex(&dbl, "gamma", "temp");
    printf("%s|%s=%s\n", "gamma", "temp", r ? r : "-");
    r = findIndex(&dbl, "delta", 0);
    printf("%s|%s=%s\n", "delta", 0, r ? r : "-");
    r = findIndex(&dbl, "delta", "main");
    printf("%s|%s=%s\n", "delta", "main", r ? r : "-");
    r = findIndex(&dbl, "delta", "temp");
    printf("%s|%s=%s\n", "delta", "temp", r ? r : "-");
    r = findIndex(&dbl, "alpha", "aux");
    printf("aux0=%s\n", r ? r : "-");
    r = findIndex(&dbl, "beta", "aux");
    printf("aux1=%s\n", r ? r : "-");
    r = findIndex(&dbl, "gamma", "aux");
    printf("aux2=%s\n", r ? r : "-");
    printf("sink=%llu\n", g_sink);
    return 0;
}
