/* FE-21: _Pragma operator (C99 6.10.9).
 *
 * _Pragma("push_macro(\"M\")") inside a macro must behave exactly like
 * #pragma push_macro("M") at that point: the pushed definition is
 * restored by the matching _Pragma("pop_macro(\"M\")") after a
 * redefinition. GCC reference semantics verified in the session doc.
 * De-stringizing must handle \\\" and \\\\ escapes per 6.10.9.1. */
#define PUSH _Pragma("push_macro(\"M\")")
#define POP  _Pragma("pop_macro(\"M\")")
#define M 1
PUSH
#undef M
#define M 2
int a = M;
POP
int b = M;

/* _Pragma generated by macro expansion of a macro argument (the operator
 * survives argument substitution). Pushing a DEFINED macro restores it. */
#define APPLY(p) p
#define N 10
APPLY(_Pragma("push_macro(\"N\")"))
#undef N
#define N 20
APPLY(_Pragma("pop_macro(\"N\")"))
int c = N;

int main(void) {
    if (a != 2) return 1;   /* M was 2 when `a` was defined */
    if (b != 1) return 2;   /* pop_macro restored M = 1 */
    if (c != 10) return 3;  /* N was pushed as 10, pop restores 10 */
    return 0;
}
